<b>Question 1</b> 

For the following matrices find an orthogonal matrix $Q$ which diagonalizes the given matrix. Also check that $Q^TAQ = D$ wjere $D$ is a diagonal matrix.

(a)$A = \begin{pmatrix}
1&0\\
0&2\\
\end{pmatrix}\quad$(b)$A = \begin{pmatrix}
1&1\\
1&1\\
\end{pmatrix}\quad$(c)$A = \begin{pmatrix}
2&1\\
1&2\\
\end{pmatrix}\quad$(d)$A = \begin{pmatrix}
5&12\\
12&-5\\
\end{pmatrix}$

<b> Solution (a)</b> 

Eigenvalue; $det(A - \lambda I) = 0$<br>

$\Rightarrow det\begin{pmatrix}
1-\lambda&0\\
0&2-\lambda\\
\end{pmatrix} = 0$

$\Rightarrow (1 - \lambda)(2 - \lambda) - 0 = 0$<br>
$\Rightarrow 2 - \lambda - 2\lambda + \lambda^2 = 0 $<br>
$\Rightarrow \lambda^2 - 3 \lambda + 2 = 0$<br>
$\Rightarrow (\lambda - 2) (\lambda - 1) = 0$

$\Rightarrow \lambda = 2, \lambda = 1$

For $\lambda_{1} = 1$ eigenvector we have $(A - \lambda I) u = 0$

$\Rightarrow \begin{pmatrix}
1-1&0\\
0 & 2-1\\
\end{pmatrix}u = 0$

$\Rightarrow \begin{pmatrix}
0&0\\
0&1\\
\end{pmatrix} \cdot \begin{pmatrix}
x\\
y\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
\end{pmatrix}$

$\Rightarrow$ eigenvector $ u = \begin{pmatrix}
1\\
0\\
\end{pmatrix}$


For $\lambda_{2} = 2$ eigenvector we have $(A - \lambda I) u = 0$

$\Rightarrow \begin{pmatrix}
1-2&0\\
0 & 2-2\\
\end{pmatrix}u = 0$

$\Rightarrow \begin{pmatrix}
-1&0\\
0&0\\
\end{pmatrix} \cdot \begin{pmatrix}
x\\
y\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
\end{pmatrix}$

$\Rightarrow$ eigenvector $ u = \begin{pmatrix}
0\\
1\\
\end{pmatrix}$

Diagonal matrix, $D$ is given by eigenvalues along the leading diagonal. Therefore, <br>
$D = \begin{pmatrix}
1&0\\
0&2\\
\end{pmatrix}$

Orthogonal matrix, Q, is given by $Q(u \quad v)$ if normalized and orthogonal. Therefore, <br>
$Q = \begin{pmatrix}
1&0\\
0&1\\
\end{pmatrix}$

Next, $Q^TAQ = \begin{pmatrix}
1&0\\
0&1\\
\end{pmatrix} \cdot \begin{pmatrix}
1&0\\
0&2\\
\end{pmatrix} \begin{pmatrix}
1&0\\
0&1\\
\end{pmatrix} = \begin{pmatrix}
1&0\\
0&2\\
\end{pmatrix} = D$

<b> Solution (b)</b> 


Here, eigevalues : $det(A - \lambda I) =0$

$\Rightarrow det\begin{pmatrix}
1- \lambda&1\\
1 & 1 - \lambda\\
\end{pmatrix} = 0$

$\Rightarrow (1 - \lambda)(1 - \lambda) - 1 = 0$<br>
$\Rightarrow (1 - \lambda)^2 - 1 = 0$<br>
$\Rightarrow 1 + \lambda^2 -2 \lambda - 1 = 0$<br>
$\Rightarrow \lambda(\lambda -2) = 0$

$\Rightarrow \lambda = 0$, $\lambda - 2$

For$\lambda_{1} = 0$,
eigenvector can be given by $(A - \lambda I)u = 0$<br>
$\Rightarrow \begin{pmatrix}
1-0&1\\
1&1-0\\
\end{pmatrix}u = 0$<br>
$\Rightarrow \begin{pmatrix}
1&1\\
1&1\\
\end{pmatrix}\cdot \begin{pmatrix}
x\\
y\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
\end{pmatrix}$

$u = \begin{pmatrix}
1\\
-1\\
\end{pmatrix}$

For eigenvector, when $\lambda_{2} = 2$

$\begin{pmatrix}
1-2&1\\
1&1-2\\
\end{pmatrix} u = 0$<br>

$\begin{pmatrix}
-1&1\\
1&-1\\
\end{pmatrix} \cdot \begin{pmatrix}
x\\
y\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
\end{pmatrix}$<br>

$\Rightarrow v = \begin{pmatrix}
1\\
1\\
\end{pmatrix}$

$A$ is symmetric matrix, therefore, eigenvector $u$ and $v$ are orthogonal.

Next, <br>

$\lVert u \rVert^2 = \lVert \begin{pmatrix}
1\\
-1\\
\end{pmatrix}\rVert^2 = \begin{pmatrix}
1\\
-1\\
\end{pmatrix} \cdot \begin{pmatrix}
1\\
-1\\
\end{pmatrix} = 1^2 + (-1)^2 = 2$

$\Rightarrow \lVert u \rVert = \sqrt{2}$

$\Rightarrow \lVert v \rVert^2 = \begin{pmatrix}
1\\
1\\
\end{pmatrix} \cdot \begin{pmatrix}
1\\
1\\
\end{pmatrix} = 2$

$\Rightarrow \lVert v \rVert = \sqrt{2}$

$\Rightarrow u = \frac{1}{\lVert u \rVert}u = \frac{1}{\sqrt{2}}\begin{pmatrix}
1\\
-1\\
\end{pmatrix}$

$\Rightarrow v = \frac{1}{\lVert v \rVert} v = \frac{1}{\sqrt{2}}\begin{pmatrix}
1\\
1\\
\end{pmatrix}$

Now, our orthogonal matrix, $Q$ is given by:
$ Q = (\widehat u \widehat v) = \frac{1}{\sqrt{2}}\begin{pmatrix}
1&1\\
-1&1\\
\end{pmatrix}$

$Q$ is an orthogonal matrix, therfore $Q^T = Q^{-1}$. 

$Q^TAQ = D$ or $QD =AQ$

$AQ = \frac{1}{\sqrt{2}}\begin{pmatrix}
1&1\\
1&1\\
\end{pmatrix} \begin{pmatrix}
1&1\\
-1&1\\
\end{pmatrix}$

$\qquad = \frac{1}{\sqrt{2}}\begin{pmatrix}
0&2\\
0&2\\
\end{pmatrix}$


$QD = \frac{1}{\sqrt{2}}\begin{pmatrix}
0&0\\
0&2\\
\end{pmatrix} \begin{pmatrix}
1&1\\
-1&1\\
\end{pmatrix}$

$\qquad = \frac{1}{\sqrt{2}}\begin{pmatrix}
0&2\\
0&2\\
\end{pmatrix}$

<b> Solution (c) </b>

Eigenvalue $det(A - \lambda I) = 0$

$\Rightarrow \begin{pmatrix}
2-\lambda&1\\
1&2-\lambda\\
\end{pmatrix} = 0$

$\Rightarrow (2 - \lambda)(2 - \lambda) -1 = 0$<br>
$\Rightarrow 4 - 4\lambda + \lambda^2 -1 = 0$<br>
$\Rightarrow \lambda^2 - 4\lambda + 3 = 0$<br>
$\Rightarrow \lambda - \lambda -3\lambda + 3 = 0$<br>
$\Rightarrow (\lambda -1)(\lambda -3) = 0$<br>
$\Rightarrow \lambda_{1} =1$ and $\lambda_{2} = 3$ 

For eigenvector, when $\lambda_{1} = 1$<br>
with $(A - \lambda I)u = 0$<br>
$\Rightarrow \begin{pmatrix}
2-1&1\\
1&2-1\\
\end{pmatrix} \cdot\begin{pmatrix}
x\\
y\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
\end{pmatrix}$

$\Rightarrow \begin{pmatrix}
1&1\\
1&1\\
\end{pmatrix} \cdot \begin{pmatrix}
x\\
y\\
\end{pmatrix}$ 

$x + y = 0$<br>
$\Rightarrow x = 1, y = -1$

Thus, eigenvector, $u = \begin{pmatrix}
1\\
-1\\
\end{pmatrix}$


For eigenvector, when $\lambda_{1} = 3$<br>
with $(A - \lambda I)u = 0$<br>
$\Rightarrow \begin{pmatrix}
2-3&1\\
1&2-3\\
\end{pmatrix} \cdot\begin{pmatrix}
x\\
y\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
\end{pmatrix}$

$\Rightarrow \begin{pmatrix}
-1&1\\
1&-1\\
\end{pmatrix} \cdot \begin{pmatrix}
x\\
y\\
\end{pmatrix}$ 

$-x + y = 0$<br>
$x - y = 0$<br>

Thus, eigenvector, $u = \begin{pmatrix}
1\\
1\\
\end{pmatrix}$

$A$ is symmetric matrix, therefore, $u$ & $v$ are orthogonal.<br>

Now, $\lVert u \rVert^2 = \begin{pmatrix}
1\\
-1\\
\end{pmatrix}^2 = 1^2 + (-1)^2 = 2$

$\Rightarrow \rVert u \lVert = \sqrt{2}$<br>
and, $u = \frac{1}{\rVert u \lVert}u = \frac{1}{\sqrt{2}}\begin{pmatrix}
1\\
-1\\
\end{pmatrix}$

Now, $\lVert v \rVert^2 = \begin{pmatrix}
1\\
1\\
\end{pmatrix}^2 = 1^2 + 1^2 = 2$

$\Rightarrow \rVert v \lVert = \sqrt{2}$<br>
and, $u = \frac{1}{\rVert v \lVert}v = \frac{1}{\sqrt{2}}\begin{pmatrix}
1\\
1\\
\end{pmatrix} $

Next, our orthogonal matrix, $Q$ is given by $Q = (\widehat u \widehat v) = \frac{1}{\sqrt{2}}\begin{pmatrix}
1&1\\
-1&1\\
\end{pmatrix}$

Diagonal matrix, $D$, is given by eigenvalues along the leading diagonal. Therefore, $D = \begin{pmatrix}
1&0\\
0&3\\
\end{pmatrix}$

$Q$ is an orthogonal matrix therefore, $Q^T = Q^{-1}$

$\Rightarrow Q^TAQ = D$<br>
$\Rightarrow QD = AQ$<br>

Here, $QD = \frac{1}{\sqrt{2}}\begin{pmatrix}
1&1\\
-1&1\\
\end{pmatrix} \cdot \begin{pmatrix}
1&0\\
0&3\\
\end{pmatrix} = \frac{1}{\sqrt{2}}\begin{pmatrix}
1&3\\
-1&3\\
\end{pmatrix}$

$\Rightarrow AQ = \frac{1}{\sqrt{2}}\begin{pmatrix}
2&1\\
1&2\\
\end{pmatrix} \cdot \begin{pmatrix}
1&1\\
-1&1\\
\end{pmatrix} = \frac{1}{\sqrt{2}}\begin{pmatrix}
1&3\\
-1&3\\
\end{pmatrix}$


<b> Solution (d) </b>

Eigenvalue $det(A - \lambda) = 0$

$\Rightarrow \begin{pmatrix}
5 - \lambda&12\\
12& -5 - \lambda\\
\end{pmatrix} = 0$<br>

$\Rightarrow (5 - \lambda)(-5 - \lambda) - 12(12) = 0$<br>
$\Rightarrow -25 -5 \lambda + 5\lambda - 144 = 0$<br>
$\Rightarrow \lambda^2 - 169 = 0$<br>
$\Rightarrow \lambda_{1} = 13$ and $\lambda_{2} = -13$

For eigenvector when $\lambda_{1} = 13$

$(A  - \lambda I)u = 0$

$\Rightarrow \begin{pmatrix}
5 - 13&12\\
12&-5-13\\
\end{pmatrix} \cdot \begin{pmatrix}
x\\
y\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
\end{pmatrix}$

$\Rightarrow \begin{pmatrix}
-8&12\\
12&-18\\
\end{pmatrix} \cdot \begin{pmatrix}
x\\
y\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
\end{pmatrix}$

$\Rightarrow -8x + 12y = 0$<br>
and, $12x - 18y = 0$<br>

$\Rightarrow x = 3, y =2$

$u = \begin{pmatrix}
3\\
2\\
\end{pmatrix}$


For eigenvector when $\lambda_{2} = -13$

$(A  - \lambda I)u = 0$

$\Rightarrow \begin{pmatrix}
5 -(-13)&12\\
12&-5-(-13)\\
\end{pmatrix} \cdot \begin{pmatrix}
x\\
y\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
\end{pmatrix}$

$\Rightarrow \begin{pmatrix}
18&12\\
12&8\\
\end{pmatrix} \cdot \begin{pmatrix}
x\\
y\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
\end{pmatrix}$

$\Rightarrow 18x + 12y = 0$<br>
and, $12x + 18y = 0$<br>

$\Rightarrow x = -2, y =3$

$v = \begin{pmatrix}
-2\\
3\\
\end{pmatrix}$

Now, $A$ is symmetric, therefore, $u$ and $v$ are orthogonal. 
Next, <br>

$\rVert u \lVert^2 = \begin{pmatrix}
3\\
2\\
\end{pmatrix} = 3^2 + 2^2 = 13$

$\Rightarrow \rVert u \lVert = \sqrt{13}$

$\Rightarrow u = \frac{1}{\rVert u \lVert} u = \frac{1}{\sqrt{13}}\begin{pmatrix}
3\\
2\\
\end{pmatrix}$



$\rVert v \lVert^2 = \begin{pmatrix}
-2\\
3\\
\end{pmatrix} = (-2)^2 + 3^2 = 13$

$\Rightarrow \rVert v \lVert = \sqrt{13}$

$\Rightarrow v = \frac{1}{\rVert v \lVert} v = \frac{1}{\sqrt{13}}\begin{pmatrix}
-2\\
3\\
\end{pmatrix}$

With this, orthogonal matrix, $Q$, is given by: 

$Q = (\widehat u \widehat v) = \frac{1}{\sqrt{13}}\begin{pmatrix}
3&-2\\
2&3\\
\end{pmatrix}$

Diagonal matrix, $D$ is given by eigenvalues along the leading diagonal. 
Then, <br>
$D = \begin{pmatrix}
13&0\\
0&-13\\
\end{pmatrix}$

$Q$ is an orthogonal matrix, therfore, $Q^T = A^{-1}$
$\Rightarrow Q^TAQ = D$ can be written as:<br>
$QD = AQ$

Now, $AQ = \frac{1}{\sqrt{13}}\begin{pmatrix}
5&12\\
12&-5\\
\end{pmatrix} \cdot \begin{pmatrix}
3&-2\\
2&3\\
\end{pmatrix}$

$\qquad = \frac{1}{\sqrt{13}}\begin{pmatrix}
15+24&-10+36\\
36-10&-24-15\\
\end{pmatrix}$<br> $\qquad= \frac{1}{\sqrt{13}}\begin{pmatrix}
39&26\\
26&-39\\
\end{pmatrix}$

$QD = \frac{1}{\sqrt{13}}\begin{pmatrix}
3&-2\\
2&3\\
\end{pmatrix} \cdot \begin{pmatrix}
13&0\\
0&13\\
\end{pmatrix}$

$\qquad = \frac{1}{\sqrt{13}}\begin{pmatrix}
39&26\\
26&-39\\
\end{pmatrix}$

Thus, $AQ = QD$

-----------------  

<b> Question 2</b> 

For the following matrices find an orthogonal matrix $Q$ which diagonalizes the given matrix. Also check that, $Q^TAQ = D$ where $D$ is the diagonal matrix.

(a)$A = \begin{pmatrix}
9&3\\
3&1\\
\end{pmatrix}\quad$(b)$A = \begin{pmatrix}
3&\sqrt{2}\\
\sqrt{2}&2\\
\end{pmatrix}\quad$(c)$A = \begin{pmatrix}
-5&\sqrt{3}\\
\sqrt{3}&-3\\
\end{pmatrix}\quad$(d)$A =  \begin{pmatrix}
4&\sqrt{12}\\
\sqrt{12}&1\\
\end{pmatrix}\quad$


<b> Solution (a)</b> 

Eigenvalue $det(A - \lambda) = 0$

$\begin{pmatrix}
9 - \lambda & 3\\
3 & 1 - \lambda \\
\end{pmatrix} = 0$

$\Rightarrow (9 - \lambda)(1 - \lambda) - 9 = 0$<br>
$\Rightarrow 9 -9 \lambda - \lambda + \lambda^2 - 9 = 0$<br>
$\Rightarrow \lambda^2 - 10 \lambda = 0$<br>
$\Rightarrow \lambda(\lambda - 10) = 0$<br>
$\Rightarrow \lambda_{1} = 0$ or $\lambda_{2} = 10$ 

For eigenvector, when $\lambda_{1} = 0$

$\begin{pmatrix}
9-0&3\\
3&1-0\\
\end{pmatrix} \begin{pmatrix}
x\\
y\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
\end{pmatrix}$

$\Rightarrow \begin{pmatrix}
9&3\\
3&1\\
\end{pmatrix} \cdot \begin{pmatrix}
x\\
y\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
\end{pmatrix}$

$\Rightarrow 9x + 3y = 0$<br>
and, $3x + 1y = 0$<br>

$\Rightarrow x = -1$ or $y = 3$

$u = \begin{pmatrix}
-1\\
3\\
\end{pmatrix}$


For eigenvector, when $\lambda_{2} = 10$

$\begin{pmatrix}
9-10&3\\
3&1-10\\
\end{pmatrix} \begin{pmatrix}
x\\
y\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
\end{pmatrix}$

$\Rightarrow \begin{pmatrix}
-1&3\\
3&-9\\
\end{pmatrix} \cdot \begin{pmatrix}
x\\
y\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
\end{pmatrix}$

$\Rightarrow -x + 3y = 0$<br>
and, $3x -9y = 0$<br>

$\Rightarrow x = 3$ or $y = 1$

$v = \begin{pmatrix}
3\\
1\\
\end{pmatrix}$


Now, $A$ is symmetric therefore $u$ and $v$ are orthogonal

$\rVert u \lVert^2 = \rVert \begin{pmatrix}
-1\\
3\\
\end{pmatrix} \lVert^2 = (-1)^2 + 3^2 = 10$

$\rVert u \lVert = \sqrt{10}$<br>

$\Rightarrow u = \frac{1}{\rVert u \lVert}u = \frac{1}{\sqrt{10}}\begin{pmatrix}
-1\\
3\\
\end{pmatrix}$


$\rVert v \lVert^2 = \rVert \begin{pmatrix}
3\\
1\\
\end{pmatrix} \lVert^2 = 3^2 + 1^2 = 10$

$\rVert v \lVert = \sqrt{10}$<br>

$\Rightarrow v = \frac{1}{\rVert v \lVert}v = \frac{1}{\sqrt{10}}\begin{pmatrix}
3\\
1\\
\end{pmatrix}$

With this, orthogonal matrix, $Q$, is given by:

$Q = (\widehat u  \widehat v) = \frac{1}{\sqrt{10}}\begin{pmatrix}
-1&3\\
3&1\\
\end{pmatrix}$

Diagonal matrix, $D$, is given by eigenvalues along the leading diagonal. Then, <br>
$D = \begin{pmatrix}
0&0\\
0&10\\
\end{pmatrix}$

$Q$ is an orthogonal matrix therefore, $Q^T = Q^{-1}$

$\Rightarrow Q^TAQ = D$ can be written as: $QD = AQ$

Now, $QD = \frac{1}{\sqrt{10}}\begin{pmatrix}
-1&3\\
3&1\\
\end{pmatrix} \cdot \begin{pmatrix}
0&0\\
0 &10\\
\end{pmatrix}$

$\qquad = \frac{1}{\sqrt{10}}\begin{pmatrix}
0&30\\
0&10\\
\end{pmatrix}$

$AQ = \frac{1}{\sqrt{10}}\begin{pmatrix}
9&3\\
3&1\\
\end{pmatrix} \cdot \begin{pmatrix}
-1&3\\
3&1\\
\end{pmatrix}$

$\qquad = \frac{1}{\sqrt{10}}\begin{pmatrix}
-9+9&27+3\\
-3+3&9+1\\
\end{pmatrix}$

$\qquad = \frac{1}{\sqrt{10}}\begin{pmatrix}
0&30\\
0&10\\
\end{pmatrix}$

<b>Hence, $QD = AQ$</b>

<b> Solution (b) </b>

Eigenvalues $det(A - \lambda) = 0$

$\Rightarrow \begin{pmatrix}
3 - \lambda& \sqrt{2}\\
\sqrt{2} & 2 - \lambda\\
\end{pmatrix} = 0$

$\Rightarrow (3 - \lambda)(2 - \lambda) - \sqrt{2}\sqrt{2} = 0$<br>
$\Rightarrow 6 - 2\lambda - 3\lambda + \lambda^2 - 2 = 0$<br>

$\Rightarrow \lambda^2 - \lambda -4 \lambda + 4 = 0$<br>
$\Rightarrow \lambda(\lambda -1) - 4(\lambda -1) = 0$<br>
$\Rightarrow (\lambda -4)(\lambda - 1) = 0$<br>
$\Rightarrow \lambda = 4$ or $\lambda = 1$

For eigenvector, when $\lambda_{1} = 4$

$\Rightarrow (A - \lambda I)u = 0$

$\Rightarrow \begin{pmatrix}
3-4&\sqrt{2}\\
\sqrt{2}&2-4\\
\end{pmatrix} \cdot \begin{pmatrix}
x\\
y\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
\end{pmatrix}$

$\Rightarrow \begin{pmatrix}
-1&\sqrt{2}\\
\sqrt{2}&-2\\
\end{pmatrix} \cdot \begin{pmatrix}
x\\
y\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
\end{pmatrix}$

$\Rightarrow -x + \sqrt{2}y = 0$<br>
and, $\sqrt{2}x - 2y = 0$

$\Rightarrow x= 2$ or $y = \sqrt{2}$

$\Rightarrow u = \begin{pmatrix}
2\\
\sqrt{2}\\
\end{pmatrix}$


For eigenvector, when $\lambda_{2} = 1$

$\Rightarrow (A - \lambda I)u = 0$

$\Rightarrow \begin{pmatrix}
3-1&\sqrt{2}\\
\sqrt{2}&2-1\\
\end{pmatrix} \cdot \begin{pmatrix}
x\\
y\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
\end{pmatrix}$

$\Rightarrow \begin{pmatrix}
2&\sqrt{2}\\
\sqrt{2}&1\\
\end{pmatrix} \cdot \begin{pmatrix}
x\\
y\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
\end{pmatrix}$

$\Rightarrow -2x + \sqrt{2}y = 0$<br>
and, $\sqrt{2}x + 1y = 0$

$\Rightarrow x= \sqrt{2}$ or $y = -2$

$\Rightarrow v = \begin{pmatrix}
\sqrt{2}\\
-2\\
\end{pmatrix}$

Now, $A$ is symmetric, therefore, $u$ and $v$ are orthogonal. <br>
Next,<br>
$\lVert u \rVert^2 = \begin{pmatrix}
2\\
\sqrt{2}\\
\end{pmatrix} = 2^2 + (\sqrt{2})^2 = 6$<br>
$\Rightarrow \lVert u \rVert = \sqrt{6}$<br>

$u = \frac{1}{\lVert u \rVert}u = \frac{1}{\sqrt{6}}\begin{pmatrix}
2\\
\sqrt{2}\\
\end{pmatrix}$


$\lVert v \rVert^2 = \begin{pmatrix}
\sqrt{2}\\
-2\\
\end{pmatrix} = \sqrt{2}^2 + (-2)^2 = 6$<br>
$\Rightarrow \lVert v \rVert = \sqrt{6}$<br>

$u = \frac{1}{\lVert v \rVert}v = \frac{1}{\sqrt{6}}\begin{pmatrix}
\sqrt{2}\\
-2\\
\end{pmatrix}$

With this, orthogonal matrix, $Q$, is given by:<br>
$Q = (\widehat u \widehat v) = \frac{1}{\sqrt{6}}\begin{pmatrix}
2&\sqrt{2}\\
\sqrt{2}&-2\\
\end{pmatrix}$

Diagonal matrix, $D$ is given eigenvalues along the leading diagonal

$D = \begin{pmatrix}
4&0\\
0&1\\
\end{pmatrix}$

$Q$ is an orthogonal matrix, therefore, $Q^T = Q^{-1}$

$\Rightarrow Q^TAQ = D$ can be written as: $QD = AQ$

$QD = \frac{1}{\sqrt{6}}\begin{pmatrix}
2&\sqrt{2}\\
\sqrt{2}&-2\\
\end{pmatrix} \cdot \begin{pmatrix}
4&0\\
0&1\\
\end{pmatrix}$

$\qquad = \frac{1}{\sqrt{6}}\begin{pmatrix}
8&\sqrt{2}\\
4\sqrt{2}&-2\\
\end{pmatrix}$


$AQ = \frac{1}{\sqrt{6}}\begin{pmatrix}
3&\sqrt{2}\\
\sqrt{2}&2\\
\end{pmatrix} \cdot \begin{pmatrix}
2&\sqrt{2}\\
\sqrt{2}&-2\\
\end{pmatrix}$

$\qquad = \frac{1}{\sqrt{6}}\begin{pmatrix}
6+2 & 3\sqrt{2} - 2\sqrt{2}\\
2\sqrt{2} + 2\sqrt{2} & 2 -4\\
\end{pmatrix}$

$\qquad = \frac{1}{\sqrt{6}}\begin{pmatrix}
8&\sqrt{2}\\
4\sqrt{2}&-2\\
\end{pmatrix}$

<b> Solution (c) </b>

Eigenvalue: $det(A - \lambda) = 0$<br>
$\Rightarrow \begin{pmatrix}
-5-\lambda & \sqrt{3}\\
\sqrt{3} & -3 - \lambda\\
\end{pmatrix} = 0$

$\Rightarrow (-5 - \lambda)(-3 - \lambda) - \sqrt{13}\sqrt{13}$<br>

$\Rightarrow 15 + 5\lambda + 3\lambda + \lambda^2 - 3= 0$<br>
$\Rightarrow \lambda^2 + 8 \lambda + 12 = 0$<br>
$\Rightarrow \lambda^2 + 6 \lambda + 2 \lambda + 12 = 0$<br>
$\Rightarrow \lambda(\lambda + 6) + 2(\lambda + 6) = 0$<br>
$\Rightarrow \lambda = -6$ or $\lambda = -2$

For eigenvector when $\lambda_{1} = -6$<br>
with $(A - \lambda I)u = 0$

we get, $\begin{pmatrix}
-5+6& \sqrt{3}\\
\sqrt{3}& -3+ 6\\
\end{pmatrix} \cdot \begin{pmatrix}
x\\
y\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
\end{pmatrix}$

$\Rightarrow \begin{pmatrix}
1&\sqrt{3}\\
\sqrt{3}&-3\\
\end{pmatrix} \cdot \begin{pmatrix}
x\\
y\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
\end{pmatrix}$

$\Rightarrow x + \sqrt{3}y = 0$<br>
and, $\sqrt{3} + 3y = 0$

$\Rightarrow x = -3, y = \sqrt{3}$

$u = \begin{pmatrix}
-3\\
\sqrt{3}\\
\end{pmatrix}$

For eigenvector when $\lambda_{1} = -2$<br>
with $(A - \lambda I)u = 0$

we get, $\begin{pmatrix}
-5+2& \sqrt{3}\\
\sqrt{3}& -3+ 2\\
\end{pmatrix} \cdot \begin{pmatrix}
x\\
y\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
\end{pmatrix}$

$\Rightarrow \begin{pmatrix}
-3&\sqrt{3}\\
\sqrt{3}&-1\\
\end{pmatrix} \cdot \begin{pmatrix}
x\\
y\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
\end{pmatrix}$

$\Rightarrow -3x + \sqrt{3}y = 0$<br>
and, $\sqrt{3}x  -y = 0$

$\Rightarrow x = \sqrt{3}, y = 3$

$v = \begin{pmatrix}
\sqrt{3}\\
-3\\
\end{pmatrix}$


Now, $A$ is symmetric, therefore, $u$ and $v$ are orthogonal. <br>
Next,<br>
$\lVert u \rVert^2 = \begin{pmatrix}
-3\\
\sqrt{3}\\
\end{pmatrix} = (-3)^2 + (\sqrt{3})^2 = 12$<br>
$\Rightarrow \lVert u \rVert = \sqrt{12}$<br>

$u = \frac{1}{\lVert u \rVert}u = \frac{1}{\sqrt{12}}\begin{pmatrix}
-3\\
\sqrt{3}\\
\end{pmatrix}$


$\lVert v \rVert^2 = \begin{pmatrix}
\sqrt{3}\\
3\\
\end{pmatrix} = \sqrt{3}^2 + (3)^2 = 12$<br>
$\Rightarrow \lVert v \rVert = \sqrt{12}$<br>

$u = \frac{1}{\lVert v \rVert}v = \frac{1}{\sqrt{12}}\begin{pmatrix}
\sqrt{3}\\
3\\
\end{pmatrix}$

With this, orthogonal matrix, $Q$, is given by:<br>
$Q = (\widehat u \widehat v) = \frac{1}{\sqrt{12}}\begin{pmatrix}
-3&\sqrt{3}\\
\sqrt{3}&3\\
\end{pmatrix}$

Diagonal matrix, $D$ is given eigenvalues along the leading diagonal

$D = \begin{pmatrix}
-6&0\\
0&-2\\
\end{pmatrix}$

$Q$ is an orthogonal matrix, therefore, $Q^T = Q^{-1}$

$\Rightarrow Q^TAQ = D$ can be written as: $QD = AQ$

$QD = \frac{1}{\sqrt{12}}\begin{pmatrix}
-3&\sqrt{13}\\
\sqrt{13}&3\\
\end{pmatrix} \cdot \begin{pmatrix}
-6&0\\
0&-2\\
\end{pmatrix}$


$\qquad = \frac{1}{\sqrt{12}}\begin{pmatrix}
18+0 & 0 - 2\sqrt{3}\\
-6\sqrt{3}+0 & 0 -6\\
\end{pmatrix}$

$\qquad = \frac{1}{12}\begin{pmatrix}
18&-2\sqrt{3}\\
-6\sqrt{3}&-6\\
\end{pmatrix}$

$AQ = \frac{1}{\sqrt{12}}\begin{pmatrix}
-5&\sqrt{13}\\
\sqrt{3}&-3\\
\end{pmatrix} \cdot \begin{pmatrix}
-3&\sqrt{3}\\
\sqrt{3}&3\\
\end{pmatrix}$


$\qquad = \frac{1}{\sqrt{12}}\begin{pmatrix}
15 +3 & -5\sqrt{3} + 3\sqrt{3}\\
-3\sqrt{3} - 3\sqrt{3}& 3 -9\\
\end{pmatrix}$

$\qquad = \frac{1}{12}\begin{pmatrix}
18&-2\sqrt{3}\\
-6\sqrt{3}&-6\\
\end{pmatrix}$

<b>Solution (d) </b> 

Eigenvalue: $det(A - \lambda I) = 0$

$\Rightarrow \begin{pmatrix}
5 - \lambda & \sqrt{12}\\
\sqrt{12} & 1 - \lambda\\
\end{pmatrix} = 0$<br>

$\Rightarrow (5 - \lambda)(1 - \lambda) - \sqrt{12}\sqrt{12} = 0$<br>
$\Rightarrow 5- 5\lambda - \lambda + \lambda^2 - 12 = 0$<br>
$\Rightarrow \lambda^2 - 6\lambda - 7 = 0$<br>
$\Rightarrow \lambda^2 - 7 \lambda + \lambda - 7 =0 $<br>
$\Rightarrow (\lambda + 1)(\lambda - 7) = 0$

$\Rightarrow \lambda = -1$ or $\lambda = 7$

For eigenvector when $\lambda_{1} = -1$<br>
with, $(A - \lambda I)u = 0$<br>

$\Rightarrow \begin{pmatrix}
5+1 & \sqrt{12}\\
\sqrt{12} & 2 \\
\end{pmatrix} \cdot \begin{pmatrix}
x\\
y\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
\end{pmatrix}$

$\Rightarrow \begin{pmatrix}
6 & \sqrt{12}\\
\sqrt{12} & 2 \\
\end{pmatrix} \cdot \begin{pmatrix}
x\\
y\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
\end{pmatrix}$

$\Rightarrow 6x + \sqrt{12}y = 0$<br>
and, $\sqrt{12}x + 2y = 0$

$\Rightarrow x = -2$ or $y = \sqrt{12}$

$u = \begin{pmatrix}
-2\\
\sqrt{12}\\
\end{pmatrix}$


For eigenvector when $\lambda_{2} = 7$<br>
with, $(A - \lambda I)u = 0$<br>

$\Rightarrow \begin{pmatrix}
5-7 & \sqrt{12}\\
\sqrt{12} & 1-7 \\
\end{pmatrix} \cdot \begin{pmatrix}
x\\
y\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
\end{pmatrix}$

$\Rightarrow \begin{pmatrix}
-2 & \sqrt{12}\\
\sqrt{12} & -6 \\
\end{pmatrix} \cdot \begin{pmatrix}
x\\
y\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
\end{pmatrix}$

$\Rightarrow -2x + \sqrt{12}y = 0$<br>
and, $\sqrt{12}x + -6y = 0$

$\Rightarrow x = \sqrt{12}$ or $y = 2$

$v = \begin{pmatrix}
\sqrt{12}\\
2\\
\end{pmatrix}$

Now $A$ is symmetric matrix, therefore, $u$ and $v$ are orthogonal

$\lVert u \rVert^2 = \begin{pmatrix}
-2\\
\sqrt{12}\\
\end{pmatrix}^2 = (-2)^2 + \sqrt{12}^2 = 16$<br>
$\Rightarrow  \lVert u \rVert = \sqrt{16} = 4$<br>

$\Rightarrow u = \frac{1}{\lVert u \rVert}u = \frac{1}{4}\begin{pmatrix}
-2\\
\sqrt{12}\\
\end{pmatrix}$


$\lVert v \rVert^2 = \begin{pmatrix}
\sqrt{12}\\
2\\
\end{pmatrix}^2 = (\sqrt{12})^2 + 2^2 = 16$<br>
$\Rightarrow  \lVert v \rVert = \sqrt{16} = 4$<br>

$\Rightarrow v = \frac{1}{\lVert v \rVert}v = \frac{1}{4}\begin{pmatrix}
\sqrt{12}\\
2\\
\end{pmatrix}$

With this, orthogonal matrix, $Q$ is given by:

$Q = (\widehat u \widehat v) = \frac{1}{4}\begin{pmatrix}
-2& \sqrt{12}\\
\sqrt{12}& 2\\
\end{pmatrix}$

$\qquad = \frac{1}{2}\begin{pmatrix}
-1& \sqrt{3}\\
\sqrt{3}& 1\\
\end{pmatrix}$

Diagonal matrix, $D$ is given by eigenvalues along the leading diagonal. <br>
Thus, $D = \begin{pmatrix}
-1&0\\
0&7\\
\end{pmatrix}$

$Q$ is an orthogonal matrix, therefore $Q^T = Q^{-1}$

$\Rightarrow Q^TAQ = D$ can be written as $QD = AQ$

Here, $QD =  \frac{1}{2}\begin{pmatrix}
-1& \sqrt{3}\\
\sqrt{3}& 1\\
\end{pmatrix} \cdot \begin{pmatrix}
-1&0\\
0&7\\
\end{pmatrix}$

$\qquad = \frac{1}{2}\begin{pmatrix}
1&7\sqrt{3}\\
-\sqrt{3} & 7\\
\end{pmatrix}$

$AQ =  \frac{1}{2}\begin{pmatrix}
5& \sqrt{12}\\
\sqrt{12}& 1\\
\end{pmatrix} \cdot \begin{pmatrix}
-1&\sqrt{3}\\
\sqrt{3}&1\\
\end{pmatrix}$

$AQ =  \frac{1}{2}\begin{pmatrix}
5& 2\sqrt{3}\\
2\sqrt{3}& 1\\
\end{pmatrix} \cdot \begin{pmatrix}
-1&\sqrt{3}\\
\sqrt{3}&1\\
\end{pmatrix}$

$\qquad = \frac{1}{2}\begin{pmatrix}
1&7\sqrt{3}\\
-\sqrt{3} & 7\\
\end{pmatrix}$

Hence, $QD = AQ$

------------------

<b>Question 3</b>

For the following matrices find an orthogonal matrix $Q$ which diagonalizes the given matrix. BY using MATLAB or otherwise check that $Q^TAQ = D$ where $D$ is the diagonal matrix.

(a)$A = \begin{pmatrix}
1&0&0\\
0&2&0\\
0&0&3\\
\end{pmatrix}\quad$(b)$A = \begin{pmatrix}
2&2&2\\
2&2&2\\
2&2&2\\
\end{pmatrix}\quad$(c)$A = \begin{pmatrix}
0&0&0\\
0&1&1\\
0&1&1\\
\end{pmatrix}$

<b> Solution (a) </b> 

Since, our given matrix, $A = \begin{pmatrix}
1&0&0\\
0&2&0\\
0&0&3\\
\end{pmatrix}$ is also a diagonal matrix.

Then, we need to find an orthogonal matrix, $Q$ such that<br> $Q^TAQ = A$

If we take $Q$ equal to identity matrix, $I$, then <br>
$Q^TAQ = I^TAI$<br>
$\qquad = A$

Thus, we can say identity matrix, $I$ is the orthogonal matrix for $A$


<b> Solution (b) </b>

Eigenvalues: $det(A - \lambda I) = 0$

$\Rightarrow (2 - \lambda)\begin{pmatrix}
2-\lambda&2\\
2 & 2 - \lambda\\
\end{pmatrix} - 2\begin{pmatrix}
2&2\\
2&2-\lambda\\
\end{pmatrix} + 2\begin{pmatrix}
2&2-\lambda\\
2&2\\
\end{pmatrix} = 0$

$\Rightarrow (2 - \lambda)[(2- \lambda)(2 - \lambda) -4] -2[2(2 - \lambda) -4] + 2[4 - 2(2-\lambda)] = 0$<br>
$\Rightarrow (2 - \lambda)(4 - 4\lambda + \lambda^2 + 4) - 2(4 - 2\lambda - 4) + 2(4-4 + 2\lambda) = 0$<br>
$\Rightarrow 2\lambda^2 - 8 \lambda - \lambda^3 + 4\lambda + 8 \lambda = 0$<br>
$\Rightarrow \lambda^3 - 6\lambda^2 = 0$<br>
$\Rightarrow \lambda^2 (\lambda - 6) = 0$<br>
$\Rightarrow \lambda^2 = 0$ and $\lambda = 6$

Hence, we can write eigenvalues as $\lambda_{1} = 0, \lambda_{2} = 0$ and $\lambda_{3} = 6$

For eigenvector when $\lambda_{1} = 0$, <br>
with $(A - \lambda I)u = 0$<br>
we get, <br>

$\begin{pmatrix}
2-0&2&2\\
2&2-0&2\\
2&2&2-0\\
\end{pmatrix} \begin{pmatrix}
x\\
y\\
z\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
0\\
\end{pmatrix}$

$\Rightarrow 2x + 2y + 2z  =0$<br>
and, $2x + 2y + 2z  =0$<br>
and, $2x + 2y + 2z  =0$

This system of equations can have any values for $x, y$ and $z$. Howeverm here we are looking for orthogonal matrix, therefore we need to pick values of $x, y$ and $z$ for eigenvector $u$ and $v$ such that $u \cdot v = 0$

For example, if $u = \begin{pmatrix}
1\\
-1\\
0\\
\end{pmatrix}$, and $v = \begin{pmatrix}
1\\
1\\
-2\\
\end{pmatrix}$ we have $u \cdot v = 0$

Next, for eigenvector when $\lambda_{3} = 6$

we get, $\begin{pmatrix}
2-6&2&2\\
2&2-6&2\\
2&2&2-6\\
\end{pmatrix} \cdot \begin{pmatrix}
x\\
y\\
z\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
0\\
\end{pmatrix}$

$\Rightarrow -4x + 2y + 2z = 0$<br>
and, $2x - 4y + 2z = 0$<br>
and, $2x + 2y -4z = 0$<br>

$\Rightarrow x = y= z = 1$

Therefore, third eigenvector $w = \begin{pmatrix}
1\\
1\\
1\\
\end{pmatrix}$

Now, normalizing eigenvector

$\lVert u \rVert^2 = \lVert \begin{pmatrix}
1\\
-1\\
0\\
\end{pmatrix}^2 \rVert = 1^2 + (-1)^2 + 0^2 = 2$<br>

$ \lVert u \rVert = \sqrt{2}$<br>

$\Rightarrow \widehat u = \frac{1}{\lVert u \rVert} u = \frac{1}{\sqrt{2}}\begin{pmatrix}
1\\
-1\\
0\\
\end{pmatrix}$


$\lVert v \rVert^2 = \lVert \begin{pmatrix}
1\\
1\\
-2\\
\end{pmatrix}^2 \rVert = 1^2 + 1^2 + (-2)^2 = 6$<br>

$ \lVert v \rVert = \sqrt{6}$<br>

$\Rightarrow \widehat v = \frac{1}{\lVert v \rVert} v = \frac{1}{\sqrt{6}}\begin{pmatrix}
1\\
1\\
-2\\
\end{pmatrix}$


$\lVert w \rVert^2 = \lVert \begin{pmatrix}
1\\
1\\
1\\
\end{pmatrix}^2 \rVert = 1^2 + 1^2 + 1^2 = 3$<br>

$ \lVert w \rVert = \sqrt{3}$<br>

$\Rightarrow \widehat w = \frac{1}{\lVert w \rVert} w = \frac{1}{\sqrt{3}}\begin{pmatrix}
1\\
1\\
1\\
\end{pmatrix}$

Orthogonal matrix, $Q$ is given by $Q = (\widehat u \widehat v \widehat w)$

$\Rightarrow Q = \begin{pmatrix}
1/\sqrt{2}& 1/\sqrt{6} & 1/\sqrt{3}\\
-1/\sqrt{2}& 1/\sqrt{6} & 1/\sqrt{3}\\
0& -2/\sqrt{6} & 1/\sqrt{3}\\
\end{pmatrix}$


In this case, diagonal matrix, with eigenvalues along the leading diagonal would be :

$D = \begin{pmatrix}
0&0&0\\
0&0&0\\
0&0&6\\
\end{pmatrix}$

Next using Scipy to get $Q^TAQ$ and check if it's equal to $D$

In [14]:
import numpy as np

matrix1 = np.array([
    [1/np.sqrt(2), 1/np.sqrt(6), 1/np.sqrt(3)],
    [-1/np.sqrt(2), 1/np.sqrt(6), 1/np.sqrt(3)],
    [0, -2/np.sqrt(6), 1/np.sqrt(3)]
])

matrix2 = np.array([
    [2, 2, 2],
    [2, 2, 2],
    [2, 2, 2]
])

matrix3 = np.array([
    [1/np.sqrt(2), 1/np.sqrt(6), 1/np.sqrt(3)],
    [-1/np.sqrt(2), 1/np.sqrt(6), 1/np.sqrt(3)],
    [0, -2/np.sqrt(6), 1/np.sqrt(3)]
])

result = np.matmul(np.matmul(matrix1.T, matrix2), matrix3)

# Round the elements to two decimal points
result_rounded = np.round(result, 2)

print("Resultant matrix of Q^TAQ")
print(result_rounded)


Resultant matrix of Q^TAQ
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [-0.  0.  6.]]


<b> Solution (c)</b>

Eigenvalues: $det(A - \lambda I) = 0$

$\Rightarrow \begin{pmatrix}
-\lambda &0 &0\\
0 & 1-\lambda&1\\
0&1&1-\lambda\\
\end{pmatrix} = 0$<br>

$\Rightarrow -\lambda[(1-\lambda)(1-\lambda) -1] - 0[0(1-\lambda) - 0(1)] + 0[0(1) -0(1)] = 0$<br>

$\Rightarrow -\lambda(1 - 2\lambda + \lambda^2 -1) = 0$<br>
$\Rightarrow -\lambda^3 + 2\lambda^2 = 0$<br>
$\Rightarrow \lambda^3 - 2\lambda^2 = 0$<br>
$\Rightarrow \lambda^2 (\lambda -2) = 0$<br>

$\Rightarrow \lambda^2 = 0$ or $\lambda = 2$

Here, we can write eigenvalues as $\lambda_{1} = 0, \lambda_{2} = 0$ and $\lambda_{3} =2$

For eigenvectors when $\lambda_{1} = 0$<br>
with $(A - \lambda I) u = 0$, 

we get, <br>
$\begin{pmatrix}
0-0&0&0\\
0&1-0&1\\
0&1&1-0\\
\end{pmatrix} \begin{pmatrix}
x\\
y\\
z\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
0\\
\end{pmatrix}$

$\Rightarrow 0x + y + z = 0$<br>
and, $0x + y + z = 0$

$\Rightarrow y = -z$ or $u = \begin{pmatrix}
0\\
-1\\
1\\
\end{pmatrix}$

However, we are looking for orthogonal matrix, we need to pick values of $x, y$ and $z$ for $v$ such that $u \cdot v = 0$ if $v = \begin{pmatrix}
1\\
0\\
0\\
\end{pmatrix}$ then we have $u \cdot v = 0$

Next, for eigenvector when $\lambda_{3} = 2$, 

we get $\begin{pmatrix}
0-2&0&0\\
0&1-2&1\\
0&1&1-2\\
\end{pmatrix} \begin{pmatrix}
x\\
y\\
z\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
0\\
\end{pmatrix}$

$\Rightarrow -2x = 0$<br>
and, $-y + z = 0$<br>
and, $y - z = 0$

$\Rightarrow x  =0$ and $y =z$ where $y$ and $z$ can be any non-zero

Therefore, $w = \begin{pmatrix}
0\\
1\\
1\\
\end{pmatrix}$

Now, normalizing eigenvectors

$\lVert u \rVert^2 = \lVert \begin{pmatrix}
0\\
-1\\
1\\
\end{pmatrix} \rVert^2 = 0^2 + (-1)^2 + 1^2 = 2$

$\Rightarrow \lVert u \rVert = \sqrt{2}$

$\Rightarrow \widehat u = \frac{1}{\lVert u \rVert}u = \frac{1}{\sqrt{2}}  \begin{pmatrix}
0\\
-1\\
1\\
\end{pmatrix}$

$\lVert v \rVert^2 = \lVert \begin{pmatrix}
1\\
0\\
0\\
\end{pmatrix} \rVert^2 = 1^2 + 0^2 + 0^2 = 1$

$\Rightarrow \lVert v \rVert = \sqrt{1} = 1$

$\Rightarrow \widehat v = \frac{1}{\lVert v \rVert}v = \begin{pmatrix}
1\\
0\\
0\\
\end{pmatrix}$

$\lVert w \rVert^2 = \lVert \begin{pmatrix}
0\\
1\\
1\\
\end{pmatrix} \rVert^2 = 0^2 + 1^2 + 1^2 = 2$

$\Rightarrow \lVert w \rVert = \sqrt{2}$

$\Rightarrow \widehat w = \frac{1}{\lVert w \rVert}w = \frac{1}{\sqrt{2}}  \begin{pmatrix}
0\\
1\\
1\\
\end{pmatrix}$

Orthogonal matrix, $Q$ is given by $Q = (\widehat u \widehat v \widehat w)$

Therefore, $Q = \begin{pmatrix}
0&1&0\\
-1/\sqrt{2}&0&1/\sqrt{2}\\
1/\sqrt{2}&0&1/\sqrt{2}\\
\end{pmatrix}$


In this case, diagonal matrix, with eigenvalues along the leading diagonal would be :

$D = \begin{pmatrix}
0&0&0\\
0&0&0\\
0&0&2\\
\end{pmatrix}$

Next using Scipy to get $Q^TAQ$ and check if it's equal to $D$

In [15]:
import numpy as np

# Define the matrices
matrix1 = np.array([
    [0, 1, 0],
    [-1/np.sqrt(2), 0, 1/np.sqrt(2)],
    [1/np.sqrt(2), 0, 1/np.sqrt(2)]
])

matrix2 = np.array([
    [0, 0, 0],
    [0, 1, 1],
    [0, 1, 1]
])

matrix3 = np.array([
    [0, 1, 0],
    [-1/np.sqrt(2), 0, 1/np.sqrt(2)],
    [1/np.sqrt(2), 0, 1/np.sqrt(2)]
])

# Perform the matrix multiplications
result = np.matmul(np.matmul(matrix1.T, matrix2), matrix3)
result_rounded = np.round(result, 2)

print("Resultant matrix:")
print(result_rounded)


Resultant matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 2.]]


------------------------------- 

<b> Question 4 </b> 

For the following matrices find an orthogonal matrix $Q$ which diagonalizes the given matrix. BY using MATLAB or otherwise check that $Q^TAQ = D$.

(a)$A = \begin{pmatrix}
1&2&2\\
2&1&2\\
2&2&1\\
\end{pmatrix}\quad$(b)$A = \begin{pmatrix}
2&1&1\\
1&2&1\\
1&1&2\\
\end{pmatrix}\quad$(c)$A = \begin{pmatrix}
-5&4&2\\
4&-5&2\\
2&2&-8\\
\end{pmatrix}$

<b>Solution (a) </b>

Eigenvalue: $det(A - \lambda I) = 0$

$\Rightarrow \begin{pmatrix}
1-\lambda& 2 & 2\\
2 & 1 - \lambda & 2\\
2 & 2 & 1 - \lambda\\
\end{pmatrix} = 0$

$\Rightarrow (1- \lambda)[(1 - \lambda)(1 - \lambda) - 2(2)] - 2[2(1- \lambda) -2(2)] + 2[2(2) - 2(1 - \lambda)] = 0$<br>

$\Rightarrow (1- \lambda)[(1 - \lambda)^2 - 4] -2[2 - 2\lambda -4] + 2[4 -2 + 2\lambda] = 0$<br>

$\Rightarrow (1- \lambda)(1 + \lambda^2 -2\lambda - 4) -2(-2\lambda -2) + 2(2\lambda + 2) = 0$<br>

$\Rightarrow (1- \lambda)(\lambda^2 - 2\lambda -3) + 4\lambda + 4 +4\lambda + 4 = 0$<br>

$\Rightarrow \lambda^2 - 2\lambda -3 - \lambda^3 + 2\lambda^2 + 3\lambda + 8\lambda +8 = 0$<br>

$\Rightarrow -\lambda^3 + 3\lambda^2 + 9\lambda + 5 = 0$<br>
$\Rightarrow \lambda^3 - 3\lambda^2 - 9\lambda - 5 = 0$<br>

$\Rightarrow \lambda^3 -5\lambda^2 + 2\lambda^2 + \lambda - 10\lambda -5 = 0$

$\Rightarrow \lambda^3 + 2\lambda^2 + \lambda -5\lambda^2 - 10\lambda -5 = 0$

$\Rightarrow \lambda(\lambda^2 + 2\lambda + 1) - 5(\lambda^2 + 2\lambda + 1) = 0$

$\Rightarrow (\lambda - 5)(\lambda^2 + 2\lambda + 1) =0 $

$\Rightarrow (\lambda - 5)(\lambda + 1)^2 =0 $

$\Rightarrow \lambda = 5$ and $\lambda = -1$ with multiplicity of 2.

<b>Hence, our eigenvalues are $\lambda_{1} = 5, \lambda_{2} = -1$ and $\lambda_{3} = -1$</b>

Now for eigenvector when $\lambda = 5$<br>
with $(A - \lambda I) u = 0$<br>
we get, $\begin{pmatrix}
1-5&2&2\\
2&1-5&2\\
2&2&1-5\\
\end{pmatrix} \cdot \begin{pmatrix}
x\\
y\\
z\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
0\\
\end{pmatrix}$

$\Rightarrow \begin{pmatrix}
-4&2&2\\
2&-4&2\\
2&2&-4\\
\end{pmatrix} \cdot \begin{pmatrix}
x\\
y\\
z\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
0\\
\end{pmatrix}$

$\Rightarrow -4x + 2y + 2z = 0$<br>
and, $2x - 4y + 2z = 0$<br>
and, $2x + 2y -4z = 0$

$\Rightarrow x = y = z = 1$. Thus eigenvector $u = \begin{pmatrix}
1\\
1\\
1\\
\end{pmatrix}$

Next, for eigenvalues when $\lambda = -1$<br>
we get, $\begin{pmatrix}
1-(-1)&2&2\\
2&1-(-1)&2\\
2&2&1-(-1)\\
\end{pmatrix} \cdot \begin{pmatrix}
x\\
y\\
z\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
0\\
\end{pmatrix}$

$\Rightarrow \begin{pmatrix}
2&2&2\\
2&2&2\\
2&2&2\\
\end{pmatrix} \cdot \begin{pmatrix}
x\\
y\\
z\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
0\\
\end{pmatrix}$

$\Rightarrow 2x + 2y + 2z  =0$<br>
and, $2x + 2y + 2z  =0$<br>
and, $2x + 2y + 2z  =0$

This system of equations can have any values for $x, y$ and $z$. Howeverm here we are looking for orthogonal matrix, therefore we need to pick values of $x, y$ and $z$ for eigenvector $v$ and $w$ such that $v \cdot w = 0$

For example, if $v = \begin{pmatrix}
1\\
-1\\
0\\
\end{pmatrix}$, and $w = \begin{pmatrix}
1\\
1\\
-2\\
\end{pmatrix}$ we have $v \cdot w = 0$

Now, normalizing eigenvectors, 

$\lVert u \rVert^2 = \lVert \begin{pmatrix}
1\\
1\\
1\\
\end{pmatrix} \rVert^2 = 1^2 +1^2 +1^2 = 3$

$\Rightarrow \lVert u \rVert = \sqrt{3}$<br>

$\Rightarrow \widehat u = \frac{1}{\lVert u \rVert} u = \frac{1}{\sqrt{3}}\begin{pmatrix}
1\\
1\\
1\\
\end{pmatrix}$


$\lVert v \rVert^2 = \lVert \begin{pmatrix}
1\\
-1\\
0\\
\end{pmatrix} \rVert^2 = 1^2 + (-1)^2 +0^2 = 2$

$\Rightarrow \lVert v \rVert = \sqrt{2}$<br>

$\Rightarrow \widehat v = \frac{1}{\lVert v \rVert} v = \frac{1}{\sqrt{2}}\begin{pmatrix}
1\\
-1\\
0\\
\end{pmatrix}$


$\lVert w \rVert^2 = \lVert \begin{pmatrix}
1\\
1\\
-2\\
\end{pmatrix} \rVert^2 = 1^2 + 1^2 +2^2 = 6$

$\Rightarrow \lVert w \rVert = \sqrt{6}$<br>

$\Rightarrow \widehat w = \frac{1}{\lVert w \rVert} w = \frac{1}{\sqrt{6}}\begin{pmatrix}
1\\
1\\
-2\\
\end{pmatrix}$

Orthogonal matrix, $Q$ is given by $Q = (\widehat u \widehat v \widehat w)$

Thus, we can write $Q = \begin{pmatrix}
1/\sqrt{3}&1/\sqrt{2}&1/\sqrt{6}\\
1/\sqrt{3}&-1/\sqrt{2}&1/\sqrt{6}\\
1/\sqrt{3}&0&-2/\sqrt{6}\\
\end{pmatrix}$


In this case, diagonal matrix, with eigenvalues along the leading diagonal would be :

$D = \begin{pmatrix}
5&0&0\\
0&-1&0\\
0&0&-1\\
\end{pmatrix}$

Next using Scipy to get $Q^TAQ$ and check if it's equal to $D$

In [17]:
matrix1 = np.array([
    [1/np.sqrt(3), 1/np.sqrt(2), 1/np.sqrt(6)],
    [1/np.sqrt(3), -1/np.sqrt(2), 1/np.sqrt(6)],
    [1/np.sqrt(3), 0, -2/np.sqrt(6)]
])

matrix2 = np.array([
    [1, 2, 2],
    [2, 1, 2],
    [2, 2, 1]
])

matrix3 = np.array([
    [1/np.sqrt(3), 1/np.sqrt(2), 1/np.sqrt(6)],
    [1/np.sqrt(3), -1/np.sqrt(2), 1/np.sqrt(6)],
    [1/np.sqrt(3), 0, -2/np.sqrt(6)]
])

# Perform the matrix multiplications
result = np.matmul(np.matmul(matrix1.T, matrix2), matrix3)
result_rounded = np.round(result, 2)

print("Resultant matrix:")
print(result_rounded)

Resultant matrix:
[[ 5.  0. -0.]
 [ 0. -1. -0.]
 [-0.  0. -1.]]


------------------------ 

<b> Question 5</b> 

Let $A = \begin{pmatrix}
1&1\\
1&1\\
\end{pmatrix}$. Show that $A^{10} = 2^9A$. Also prove that $A^m = 2^{m-1}A$ where $m$ is a positive integer.

<b> Solution </b>

In Question <b>1(b)</b> we already have calculated  orthogonal matrix, $Q$ and diagonal matrix, $Q$ for this matrix $A$.
We have, <br>

$Q = \frac{1}{\sqrt{2}}\begin{pmatrix}
1&1\\
-1&1\\
\end{pmatrix}$, and $D = \begin{pmatrix}
0&0\\
0&2\\
\end{pmatrix}$

We also know that, <br>

$A^m = QD^mQ^T$

Therefore, <br>

$A^{10} = \frac{1}{\sqrt{2}}\begin{pmatrix}
1&1\\
-1&1\\
\end{pmatrix} \cdot \begin{pmatrix}
0&0\\
0&2\\
\end{pmatrix}^{10} \cdot \frac{1}{\sqrt{2}}\begin{pmatrix}
1&1\\
-1&1\\
\end{pmatrix}^T$

$\qquad = \frac{1}{\sqrt{2}}\frac{1}{\sqrt{2}}\begin{pmatrix}
1&1\\
-1&1\\
\end{pmatrix} \cdot \begin{pmatrix}
0&0\\
0&2^{10}\\
\end{pmatrix} \cdot \begin{pmatrix}
1&-1\\
1&1\\
\end{pmatrix}$

$\qquad = \frac{1}{2}\begin{pmatrix}
1&1\\
-1&1\\
\end{pmatrix} \cdot 2^{10} \begin{pmatrix}
0&0\\
0&1\\
\end{pmatrix} \cdot \begin{pmatrix}
1&-1\\
1&1\\
\end{pmatrix}$

$\qquad = \frac{2^{10}}{2}\begin{pmatrix}
1&1\\
-1&1\\
\end{pmatrix} \cdot \begin{pmatrix}
0&0\\
0&1\\
\end{pmatrix} \cdot \begin{pmatrix}
1&-1\\
1&1\\
\end{pmatrix}$

$\qquad = 2^9 \begin{pmatrix}
0&1\\
0&1\\
\end{pmatrix} \cdot \begin{pmatrix}
1&-1\\
1&1\\
\end{pmatrix}$

$\qquad = 2^9  \begin{pmatrix}
1&1\\
1&1\\
\end{pmatrix}$

$\qquad = 2^9A$

<b>Hence, proved $A^{10} = 2^9 A$</b>

Next, <br>

$A^m = QD^mQ^T $<br>
$\qquad = \frac{1}{\sqrt{2}}\begin{pmatrix}
1&1\\
-1&1\\
\end{pmatrix} \cdot \begin{pmatrix}
0&0\\
0&2\\
\end{pmatrix}^m \cdot \frac{1}{\sqrt{2}}\begin{pmatrix}
1&1\\
-1&1\\
\end{pmatrix}^T$


$\qquad = \frac{1}{\sqrt{2}}\frac{1}{\sqrt{2}}\begin{pmatrix}
1&1\\
-1&1\\
\end{pmatrix} \cdot \begin{pmatrix}
0&0\\
0&2^m\\
\end{pmatrix} \cdot \begin{pmatrix}
1&-1\\
1&1\\
\end{pmatrix}$

$\qquad = \frac{1}{2}\begin{pmatrix}
1&1\\
-1&1\\
\end{pmatrix} \cdot 2^m \begin{pmatrix}
0&0\\
0&1\\
\end{pmatrix} \cdot \begin{pmatrix}
1&-1\\
1&1\\
\end{pmatrix}$

$\qquad = \frac{2^m}{2}\begin{pmatrix}
1&1\\
-1&1\\
\end{pmatrix} \cdot \begin{pmatrix}
0&0\\
0&1\\
\end{pmatrix} \cdot \begin{pmatrix}
1&-1\\
1&1\\
\end{pmatrix}$


$\qquad = 2^{m-1}\begin{pmatrix}
1&1\\
1&1\\
\end{pmatrix}$

$\qquad = 2^{m-1}A$

<b>Hence, proved $A^m = 2^{m-1}$</b>

----------------------------- 

<b> Question 6</b> 

Show that if $A$ is a diagonal matrix then orthogonal diagonalizing matrix $Q = 1$

<b> Solution </b>

We have $A$ as diagonal matrix.<br>
Let's take $Q = I$<br>
Then, <br>
$Q^{-1}AQ = I^{-1} AI$<br>
$\qquad = IAI$<br>
$\qquad = A$

$\Rightarrow I$ orthogonally diagonalizes $A$.

Hence, proved if $A$ is a diagonal matrix, then orthogonally diagonalizing matrix, $Q$ is equal to identity matrix, $I$

----------------------------- 

<b> Question 7</b> 

Prove that (a) the zero matrix <b>O</b> and (b) the identity matrix $I$ are orthogonally diagonalizable

<b> Solution (a)</b>

Lets suppose our zero matrix, <b>O</b> is $3 \times 3$.

Then, <br>
Eigenvalues are $\lambda_{1} = \lambda_{2} = \lambda_{3} = 0$

Implying, eigenvectors as:

$u = \begin{pmatrix}
1\\
0\\
0\\
\end{pmatrix}, v = \begin{pmatrix}
0\\
1\\
0\\
\end{pmatrix}$, and $w = \begin{pmatrix}
0\\
0\\
1\\
\end{pmatrix}$

Normalized values of $u, v, w$ would be the same.

Therefore now, orthogonal matrix, $Q$ can be given by :

$Q = (\widehat u \widehat v \widehat w )$

$\Rightarrow Q = \begin{pmatrix}
1&0&0\\
0&1&0\\
0&0&1\\
\end{pmatrix} = I$

Then, $Q^{-1}OQ = I^{1}OI = IOI = O$

Hence, orthogonally diagonalizable.

<b> Solution (b)</b>

Since, any identity matrix, $I$ is also a diagonal matrix.
Therefore, from previous solution of question 6, we can state identity matrix is also a diagonalizable matrix, and the orthogonal matrix, $Q = I$

------------------------- 

<b> Question 8</b>

Prove that $A = \begin{pmatrix}
a&b\\
b&c\\
\end{pmatrix} \ne o$ is orthogonally diagonalizable and find the orthogonal matrix $Q$ which diagonalizes the matrix $A$.

<b> Solution </b>

Here, $A = \begin{pmatrix}
a&b\\
b&c\\
\end{pmatrix} = A^T$

Therefore, $A$ is a symmetric matrix, thus orthogonally diagonalizable

Next, Eigenvalues: $det(A - \lambda) = 0$

$det\begin{pmatrix}
a - \lambda & b\\
b & c - \lambda\\
\end{pmatrix} = 0$

$\Rightarrow (a - \lambda)(c - \lambda) - b^2 = 0$<br>

$\Rightarrow ac - \lambda a - c \lambda + \lambda^2 + b^2 = 0$<br>
$\Rightarrow \lambda^2 - (a+c)\lambda + ac - b^2$

To get eigenvalue $\lambda$, we can use quadratic equation formula: $x = \frac{-b + \sqrt{b^2 - 4ac}}{2a}$

$\Rightarrow \lambda = \frac{(a+c) \pm \sqrt{(a+c)^2 - 4(ac - b)^2}}{2(1)}$<br>

$\qquad = \frac{(a+c) \pm \sqrt{(a^2 + c^2 + 2ac - 4ac + 4b)^2}}{2}$<br>

$\qquad = \frac{(a+c) \pm \sqrt{(a^2 + c^2 -2ac + 4b)^2}}{2}$<br>

$\qquad = \frac{(a+c) \pm \sqrt{(a - c)^2 + 4b^2}}{2}$<br>

$\Rightarrow \lambda_{1} = \frac{(a+c) + \sqrt{(a - c)^2 + 4b^2}}{2}$, and $\lambda_{2} = \frac{(a+c) - \sqrt{(a - c)^2 + 4b^2}}{2}$<br>

Next, getting eigenvector for $\lambda_{1}$ 

with $(A - \lambda I) u = 0$

$(A - \lambda_{1} I) u = \begin{pmatrix}
a - \lambda_{1} &b\\
b& c - \lambda_{1}\\
\end{pmatrix} \cdot \begin{pmatrix}
x\\
y\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
\end{pmatrix}$

$\Rightarrow (a - \lambda_{1})x + by = 0$<br>
and, $bx + (c - \lambda_{1})y = 0 $

$\Rightarrow x = b$ and $y = \lambda_{1} -a$

Therefore, eigenvector $u = \begin{pmatrix}
b\\
\lambda_{1} - a\\
\end{pmatrix}$


Next, getting eigenvector for $\lambda_{2}$ 

with $(A - \lambda I) u = 0$

$(A - \lambda_{2} I) u = \begin{pmatrix}
a - \lambda_{2} &b\\
b& c - \lambda_{2}\\
\end{pmatrix} \cdot \begin{pmatrix}
x\\
y\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
\end{pmatrix}$

$\Rightarrow (a - \lambda_{2})x + by = 0$<br>
and, $bx + (c - \lambda_{2})y = 0 $

$\Rightarrow x = \lambda_{2} - c$ and $y = b$

Therefore, eigenvector $v = \begin{pmatrix}
\lambda_{2} - c\\
b\\
\end{pmatrix}$

Now, normalizing eigenvectors to get orthogonal matrix

$\lVert u \rVert^2 = \begin{pmatrix}
b\\
\lambda_{1}- a\\
\end{pmatrix} = b^2 + (\lambda_{1} - a)^2$

$\Rightarrow \lVert u \rVert = \sqrt{b^2 + (\lambda_{1} - a)^2}$

$\widehat u = \frac{1}{\lVert u \rVert}u = \frac{1}{\sqrt{b^2 + (\lambda_{1} - a)^2}}\begin{pmatrix}
b\\
\lambda_{1}- a\\
\end{pmatrix}$


$\lVert v \rVert^2 = \begin{pmatrix}
\lambda_{2} - c\\
b\\
\end{pmatrix} = (\lambda_{2} - c)^2 + b^2$

$\Rightarrow \lVert v \rVert = \sqrt{(\lambda_{2} - c)^2 + b^2}$

$\Rightarrow v = \frac{1}{\lVert v \rVert}v = \frac{1}{\sqrt{(\lambda_{2} - c)^2 + b^2}} \begin{pmatrix}
\lambda_{2} -c\\
b\\
\end{pmatrix}$

Orthogonal matrix, $Q$ is given by $Q = (\widehat u \widehat v)$

Therefore, $Q = \begin{pmatrix}
\frac{b}{\sqrt{b^2 + (\lambda_{1} - a)^2}} & \frac{\lambda_{2} - c}{(\lambda_{2} - c)^2 + b^2}\\
\frac{\lambda_{1}-a}{\sqrt{b^2 + (\lambda_{1} - a)^2}} & \frac{b}{(\lambda_{2} - c)^2 + b^2}\\
\end{pmatrix}$

--------------------- 

<b> Question 9 </b> 

Let $A$ be a symmetric invertible matrix. If $Q$ orthogonally diagonalizes the matrix $A$ show that $Q$ also diagonalizes the matrix $A^{-1}$

<b> Solution </b>

We have, $Q$ orthogonally diagonalizing matrix $A$. and we know that a matrix $A$ is orthogonally diagonalizable if is an orthogonal matrix $Q$ such that

$Q^TAQ  = D$ where $D$ is a diagonal matrix

So, we have<br>
$D  = Q^TAQ$

Next, taking inverse both side, we have

$D^{-1} = (Q^TAQ)^{-1}$<br>
$\qquad = (Q^T)^{-1}A^{-1}Q^{-1}$<br> 
$\qquad = (Q^{-1})^{-1}A^{-1}Q^{-1}$<br>
$\qquad = QA^{-1}Q^{-1}$<br> 
$\qquad = QA^{-1}Q^T$<br> 

We can see that matrix $A^{-1}$ is also diagonalizable by orthogonal matrix, $Q$ where $D^{-1}$ is a diagonal matrix.