<b>Question 1 </b>

Determine the matrices $U, D$ and $V$ such that $A = UDV^T$ for the following :

(a)$A = \begin{pmatrix}
1&0\\
0&2\\
\end{pmatrix}\quad$(b)$A = \begin{pmatrix}
1&4\\
4&7\\
\end{pmatrix}\quad$(c)$A = \begin{pmatrix}
1&0\\
0&1\\
1&2\\
\end{pmatrix}$

(d)$A = \begin{pmatrix}
1&0&1\\
0&1&2\\
\end{pmatrix}\quad$(e)$A = \begin{pmatrix}
1&1\\
3&3\\
\end{pmatrix}\quad$(f)$A = \begin{pmatrix}
1&1&1\\
3&3&3\\
\end{pmatrix}$

<b> Solution (a) </b> 

Here, $A^TA = \begin{pmatrix}
1&0\\
0&2\\
\end{pmatrix} \begin{pmatrix}
1&0\\
0&2\\
\end{pmatrix}$

$\Rightarrow A^TA = \begin{pmatrix}
1&0\\
0&4\\
\end{pmatrix}$

Eigenvalues of $A^TA: det(A - \lambda I) = 0$

$\Rightarrow \begin{pmatrix}
1- \lambda&0\\
0 & 4 - \lambda\\
\end{pmatrix} = 0$

$\Rightarrow (1- \lambda)(4 - \lambda) = 0$

$\Rightarrow \lambda_{1} =1$ and $\lambda_{2} = 4$

We know that, <br>
If $A$ is $m$ by $n$ matrix and $\lambda_{1}, \lambda_{2},...,\lambda_{n}$ be the eigenvalues of $A^TA$,, then singular values denoted by $\sigma_{1}, \sigma_{2},...\sigma_{3}$ are the numbers such that: <br>
$\sigma_{1} = \sqrt{\lambda_{1}}, \sigma_{2} = \sqrt{\lambda_{2}}$

$\Rightarrow$ <b>Here, singular values of $A$ are $\sigma_{1} = \sqrt{1} = 1$, and $\sigma_{2} = \sqrt{4} = 2$</b>

$\Rightarrow D = \begin{pmatrix}
\sigma_{1}&0\\
0&\sigma_{2}\\
\end{pmatrix} = \begin{pmatrix}
1&0\\
0&2\\
\end{pmatrix}$

Next,<br>
Eigenvector of $\lambda_{1}$

$\begin{pmatrix}
1-1&0\\
0&4-1\\
\end{pmatrix} \cdot \begin{pmatrix}
x\\
y\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
\end{pmatrix}$

$\Rightarrow \begin{pmatrix}
0&0\\
0&3\\
\end{pmatrix} \cdot \begin{pmatrix}
x\\
y\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
\end{pmatrix}$

$\Rightarrow y = 0$ and $x$ can be any non-zero $s$. Thus $v = \begin{pmatrix}
1\\
0\\
\end{pmatrix}$

and normalized eigenvector $v_{1} = \frac{1}{\lVert v \rVert}v = \frac{1}{1}v = \begin{pmatrix}
1\\
0\\
\end{pmatrix}$


Eigenvector of $\lambda_{2}$

$\begin{pmatrix}
1-4&0\\
0&4-4\\
\end{pmatrix} \cdot \begin{pmatrix}
x\\
y\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
\end{pmatrix}$

$\Rightarrow \begin{pmatrix}
-3&0\\
0&0\\
\end{pmatrix} \cdot \begin{pmatrix}
x\\
y\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
\end{pmatrix}$

$\Rightarrow x = 0$ and $y$ can be any non-zero $s$. Thus $v = \begin{pmatrix}
0\\
1\\
\end{pmatrix}$

and normalized eigenvector $v_{2} = \frac{1}{\lVert v \rVert}v = \frac{1}{1}v = \begin{pmatrix}
0\\
1\\
\end{pmatrix}$

Therefore $V = (v_{1}\quad v_{2})  =\begin{pmatrix}
1&0\\
0&1\\
\end{pmatrix}$

Next, <br>
using $\sigma_{1}u_{1} = Av_{1}$ and $\sigma_{2}u_{2} = Av_{2}$

we have, 

$u_{1} = \begin{pmatrix}
1&0\\
0&2\\
\end{pmatrix}\cdot\begin{pmatrix}
1\\
0\\
\end{pmatrix} = \begin{pmatrix}
1\\
0\\
\end{pmatrix}$

$2u_{1} = \begin{pmatrix}
1&0\\
0&2\\
\end{pmatrix}\cdot\begin{pmatrix}
0\\
1\\
\end{pmatrix} = \begin{pmatrix}
0\\
2\\
\end{pmatrix}$

$\Rightarrow u_{2} = \frac{1}{2}\begin{pmatrix}
0\\
2\\
\end{pmatrix} = \begin{pmatrix}
0\\
1\\
\end{pmatrix}$



$\Rightarrow U = (u_{1}\quad u_{2}) = \begin{pmatrix}
1&0\\
0&1\\
\end{pmatrix}$

Since, $U = V = I$<br>
$A = UDV^T = IDI^T = A$


<b> Solution (b) </b>

Here, $A^TA = \begin{pmatrix}
1&4\\
4&7\\
\end{pmatrix} \begin{pmatrix}
1&4\\
4&7\\
\end{pmatrix}$

$\qquad = \begin{pmatrix}
1+16&4+28\\
4+28&16+49\\
\end{pmatrix} = \begin{pmatrix}
17&32\\
32&65\\
\end{pmatrix}$

For Eigenvalues, $det(A - \lambda I) = 0$
we have, $\begin{pmatrix}
17-\lambda&32\\
32&65-\lambda\\
\end{pmatrix} = 0$

$\Rightarrow (17 - \lambda)(65 - \lambda) -32(32) = 0$<br>

$\Rightarrow 1105 - 17\lambda -65\lambda +\lambda^2 - 1024 = 0$<br>
$\Rightarrow \lambda^2 - 82\lambda + 81 = 0$<br>
$\Rightarrow \lambda^2 - 81\lambda -\lambda + 81 = 0$<br>
$\Rightarrow \lambda(\lambda - 81) - 1(\lambda - 81) =0$<br>
$\Rightarrow \lambda = 81$ or $\lambda = 1$


$\Rightarrow$ <b>Here, singular values of $A$ are $\sigma_{1} = \sqrt{81} = 9$, and $\sigma_{2} = \sqrt{1} = 1$</b>

$\Rightarrow D = \begin{pmatrix}
\sigma_{1}&0\\
0&\sigma_{2}\\
\end{pmatrix} = \begin{pmatrix}
9&0\\
0&1\\
\end{pmatrix}$

Next, eigenvector of $\lambda_{1} = 81$
with $(A - \lambda I) u = 0$
we get, <br>
$\begin{pmatrix}
17-81&32\\
32&65-81\\
\end{pmatrix}\begin{pmatrix}
x\\
y\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
\end{pmatrix}$

$\Rightarrow \begin{pmatrix}
-64&32\\
32&-16\\
\end{pmatrix}\begin{pmatrix}
x\\
y\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
\end{pmatrix}$

$\Rightarrow -64x + 32y = 0$<br>
and, $32x - 16y = 0$

$\Rightarrow -2x + y = 0$<br>
and, $2x - y =0$

$\Rightarrow y = 2$ and $x = 1$ or eigenvector $v = \begin{pmatrix}
1\\
2\\
\end{pmatrix}$

$\Rightarrow$ normalized eigenvector, $v_{1} = \frac{1}{\lVert v \rVert}v$<br>
$\Rightarrow v_{1} = \frac{1}{\lVert \sqrt{1^2 + 2^2} \rVert}\begin{pmatrix}
1\\
2\\
\end{pmatrix}$

$\Rightarrow v_{1} = \frac{1}{\sqrt{5}}\begin{pmatrix}
1\\
2\\
\end{pmatrix}$


Next, eigenvector of $\lambda_{1} = 1$
with $(A - \lambda I) u = 0$
we get, <br>
$\begin{pmatrix}
17-1&32\\
32&65-1\\
\end{pmatrix}\begin{pmatrix}
x\\
y\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
\end{pmatrix}$

$\Rightarrow \begin{pmatrix}
16&32\\
32&64\\
\end{pmatrix}\begin{pmatrix}
x\\
y\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
\end{pmatrix}$

$\Rightarrow 16x + 32y = 0$<br>
and, $32x + 64y = 0$

$\Rightarrow x + 2y = 0$<br>
and, $x + 2y =0$

$\Rightarrow y = 1$ and $x = -2$ or eigenvector $v = \begin{pmatrix}
-2\\
1\\
\end{pmatrix}$

$\Rightarrow$ normalized eigenvector, $v_{2} = \frac{1}{\lVert v \rVert}v$<br>
$\Rightarrow v_{2} = \frac{1}{\lVert \sqrt{(-2)^2 + 1^2} \rVert}\begin{pmatrix}
-2\\
1\\
\end{pmatrix}$

$\Rightarrow v_{2} = \frac{1}{\sqrt{5}}\begin{pmatrix}
-2\\
1\\
\end{pmatrix}$

Therefore $V = (v_{1}\quad v_{2})  =\frac{1}{\sqrt{5}}\begin{pmatrix}
1&-2\\
2&1\\
\end{pmatrix}$

Next, <br>
using $\sigma_{1}u_{1} = Av_{1}$ and $\sigma_{2}u_{2} = Av_{2}$

we have, <br>
$9u_{1} = \frac{1}{\sqrt{5}}\begin{pmatrix}
1&4\\
4&7\\
\end{pmatrix}\cdot \begin{pmatrix}
1\\
2\\
\end{pmatrix} = \frac{1}{\sqrt{5}}\begin{pmatrix}
9\\
18\\
\end{pmatrix}$

$\Rightarrow u_{1} = \frac{1}{9\sqrt{5}}\begin{pmatrix}
9\\
18\\
\end{pmatrix} = \frac{1}{\sqrt{5}}\begin{pmatrix}
1\\
2\\
\end{pmatrix}$

and, $u_{2} = \frac{1}{\sqrt{5}}\begin{pmatrix}
1&4\\
4&7\\
\end{pmatrix}\begin{pmatrix}
-2\\
1\\
\end{pmatrix} = \frac{1}{\sqrt{5}}\begin{pmatrix}
2\\
-1\\
\end{pmatrix}$


Therefore $U = (u_{1}\quad u_{2})  =\frac{1}{\sqrt{5}}\begin{pmatrix}
1&2\\
2&-1\\
\end{pmatrix}$

In [2]:
import numpy as np

# Define matrices U, D, and V
U = np.array([[1, 2], [2, -1]]) / np.sqrt(5)
D = np.array([[9, 0], [0, 1]])
V = np.array([[1, -2], [2, 1]]) / np.sqrt(5)

UDVT = np.matmul(np.matmul(U, D), V.T)

# Round the elements to two decimal points
result_rounded = np.round(UDVT, 2)

print("Resultant matrix of UDV^T")
print(result_rounded)

Resultant matrix of UDV^T
[[1. 4.]
 [4. 7.]]


<b> Solution (c) </b> 

Here, $A^TA = \begin{pmatrix}
1&0&1\\
0&1&2\\
\end{pmatrix}\begin{pmatrix}
1&0\\
0&1\\
1&2\\
\end{pmatrix}$<br>
$\qquad \Rightarrow A^TA= \begin{pmatrix}
2&2\\
2&5\\
\end{pmatrix}$

For eigenvalues, $det(A - \lambda I) = 0$<br>
we have, <br>
$\begin{pmatrix}
2-\lambda&2\\
2&5-\lambda\\
\end{pmatrix} = 0$<br>

$\Rightarrow (2-\lambda)(5-\lambda) -2(2) = 0$<br>
$\Rightarrow 10 - 2\lambda -5\lambda + \lambda^2 -4 = 0$<br>
$\Rightarrow \lambda^2 -7\lambda +6 = 0$<br>
$\Rightarrow \lambda^2 -6\lambda -\lambda +6 = 0$<br>
$\Rightarrow \lambda(\lambda - 6) -1(\lambda - 6) = 0$<br>
$\Rightarrow (\lambda - 1)(\lambda - 6) = 0$<br>

$\Rightarrow \lambda_{1} = 1$ or $\lambda_{2} = 6$ 

<b>Here, singular values of $A$ are $\sigma_{1} = \sqrt{1} = 1$ and $\sigma_{2} = \sqrt{6}$</b>

$\Rightarrow D = \begin{pmatrix}
\sigma_{1}&0\\
0&\sigma_{2}\\
\end{pmatrix} = \begin{pmatrix}
1&0\\
0&\sqrt{6}\\
0&0\\
\end{pmatrix}$


Next, <br>
eigenvector of $\lambda_{1} = 1$ with $(A - \lambda I)u = 0$<br>
we get, <br>
$\begin{pmatrix}
2-1&2\\
2&5-1\\
\end{pmatrix} \begin{pmatrix}
x\\
y\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
\end{pmatrix}$

$\Rightarrow \begin{pmatrix}
1&2\\
2&4\\
\end{pmatrix}\begin{pmatrix}
x\\
y\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
\end{pmatrix}$

$\Rightarrow x + 2y = 0$<br>
and, $2x + 4y = 0$

$\Rightarrow x= -2y$ or $x = -2$ and $y = 1$
eigenvector, $v_{1} = \begin{pmatrix}
-2\\
1\\
\end{pmatrix}$

Now, normalized eigenvector <br>

$v_{1} = \frac{1}{\lVert v_{1}\rVert}v_{1} = \frac{1}{\lVert \sqrt{(-2)^2 + 1^2}\rVert}\begin{pmatrix}
-2\\
1\\
\end{pmatrix}$

$\Rightarrow v_{1} = \frac{1}{\sqrt{5}}\begin{pmatrix}
-2\\
1\\
\end{pmatrix}$



Next, <br>
eigenvector of $\lambda_{2} = 6$ with $(A - \lambda I)u = 0$<br>
we get, <br>
$\begin{pmatrix}
2-6&2\\
2&5-6\\
\end{pmatrix} \begin{pmatrix}
x\\
y\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
\end{pmatrix}$

$\Rightarrow \begin{pmatrix}
-4&2\\
2&-1\\
\end{pmatrix}\begin{pmatrix}
x\\
y\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
\end{pmatrix}$

$\Rightarrow -4x + 2y = 0$<br>
and, $2x - y = 0$

$\Rightarrow y= 2x$ or $x = 1$ and $y = 2$
eigenvector, $v_{2} = \begin{pmatrix}
1\\
2\\
\end{pmatrix}$

Now, normalized eigenvector <br>

$v_{2} = \frac{1}{\lVert v_{2}\rVert}v_{2} = \frac{1}{\lVert \sqrt{(1^2 + 2^2}\rVert}\begin{pmatrix}
1\\
2\\
\end{pmatrix}$

$\Rightarrow v_{2} = \frac{1}{\sqrt{5}}\begin{pmatrix}
1\\
2\\
\end{pmatrix}$

Therefore, $V = (v_{1}\qquad v_{2}) = \frac{1}{\sqrt{5}}\begin{pmatrix}
-2&1\\
1&2\\
\end{pmatrix}$

Next, using $\sigma_{1}u_{1} = Av_{1}$ and $\sigma_{2}u_{2} = Av_{2}$
we have, <br>
$1\cdot u_{1} = \begin{pmatrix}
1&0\\
0&1\\
1&2\\
\end{pmatrix}\frac{1}{\sqrt{5}}\begin{pmatrix}
-2\\
1\\
\end{pmatrix}$

$\qquad = \frac{1}{\sqrt{5}}\begin{pmatrix}
1&0\\
0&1\\
1&2\\
\end{pmatrix}\begin{pmatrix}
-2\\
1\\
\end{pmatrix}$<br>
$\Rightarrow u_{1}= \frac{1}{\sqrt{5}}\begin{pmatrix}
-2\\
1\\
0\\
\end{pmatrix}$

$\sqrt{6}u_{2} =  \begin{pmatrix}
1&0\\
0&1\\
1&2\\
\end{pmatrix} \frac{1}{\sqrt{5}}\begin{pmatrix}
1\\
2\\
\end{pmatrix}$

$\Rightarrow u_{2} = \frac{1}{\sqrt{6}}\frac{1}{\sqrt{5}}\begin{pmatrix}
1&0\\
0&1\\
1&2\\
\end{pmatrix} \begin{pmatrix}
1\\
2\\
\end{pmatrix}$

$\Rightarrow u_{2} = \frac{1}{\sqrt{30}}\begin{pmatrix}
1\\
2\\
5\\
\end{pmatrix}$

We know that, <br>
any given matrix $A$ of size $m$ by $n$ can be decomposed into $A = UDV^T$<br>
where,<br>
U -> $m \times m$ orthogonal<br>
D -> $m \times n$ diagonal<br>
V -> $n \times n$ orthogonal<br>

Thus, we need to find $u_{3}$ orthogonal to $u_{1}, u_{2}$

$\Rightarrow \begin{pmatrix}
1&2&5\\
-2&1&0\\
\end{pmatrix}\begin{pmatrix}
x\\
y\\
z\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
\end{pmatrix}$

$\Rightarrow x+2y + 5z = 0$<br>
and, $-2x + y = 0$

$\Rightarrow y = 2x$ and $x = -z$

$\Rightarrow x = 1, y =2$, and $z = -1$, and $u_{3} = \begin{pmatrix}
1\\
2\\
-1\\
\end{pmatrix}$

now, normalizing $u_{3}$

$u_{3} = \frac{1}{\lVert u_{3}}u = \frac{1}{\sqrt{1^2 +2^2 + (-1)^2}} = \frac{1}{\sqrt{6}}\begin{pmatrix}
1\\
2\\
-1\\
\end{pmatrix}$

Thus, we get orthogonal $U = (u_{1}\quad u_{2}\quad u_{3}) = \begin{pmatrix}
-2/\sqrt{5}&1/\sqrt{30}&1/\sqrt{6}\\
-1/\sqrt{5}&2/\sqrt{30}&2/\sqrt{6}\\
0&5/\sqrt{30}&-1/\sqrt{6}\\
\end{pmatrix}$

In [17]:
import numpy as np

# Define the matrices
U = np.array([
    [-2/np.sqrt(5), 1/np.sqrt(30), 1/np.sqrt(6)],
    [-1/np.sqrt(5), 2/np.sqrt(30), 2/np.sqrt(6)],
    [0, 5/np.sqrt(30), -1/np.sqrt(6)]])

D = np.array([[1, 0], [0, np.sqrt(6)], [0,0]])

V = ((1/np.sqrt(5)) * np.array([[-2, 1],[1, 2]]))

UDVT = np.matmul(np.matmul(U, D), V.T)

# Round the elements to two decimal points
result_rounded = np.round(UDVT, 1)

print("Resultant matrix of UDV^T")
print(result_rounded)

Resultant matrix of UDV^T
[[ 1.  -0. ]
 [ 0.8  0.6]
 [ 1.   2. ]]


<b> Solution (d)</b>

Here, $A^TA = \begin{pmatrix}
1&0\\
0&1\\
1&2\\
\end{pmatrix} \begin{pmatrix}
1&0&1\\
0&1&2\\
\end{pmatrix} = \begin{pmatrix}
1&0&1\\
0&1&2\\
1&2&5\\
\end{pmatrix}$

For eigenvalue, $det(A - \lambda) = 0$

$\Rightarrow \begin{pmatrix}
1-\lambda&0&1\\
0&1-\lambda&2\\
1&2&5-\lambda\\
\end{pmatrix} = 0$

$\Rightarrow (1- \lambda)[(1 - \lambda)(5 - \lambda) -4] - 0[0(5 - \lambda) -1(2)] + 1[0(2) -1(1-\lambda)] = 0$<br>

$\Rightarrow (1 - \lambda)(5 - 5\lambda - \lambda + \lambda^2 -4) -1 + \lambda = 0$<br>

$\Rightarrow (1 - \lambda)(\lambda^2 - 6\lambda + 1) -1 + \lambda = 0$<br>

$\Rightarrow \lambda^2 - 6\lambda + 1 - \lambda^3 + 6 \lambda^2 -\lambda -1 + \lambda = 0$<br>

$\Rightarrow - \lambda^3 + 7 \lambda^2 -6 \lambda = 0$<br>

$\Rightarrow \lambda(\lambda^2 - 7\lambda + 6) = 0$<br>
$\Rightarrow \lambda(\lambda^2 -6\lambda -\lambda + 6) = 0$<br>
$\Rightarrow \lambda(\lambda -1)(\lambda - 6) = 0$

$\Rightarrow \lambda_{1} = 6, \lambda_{2} = 1$ and $\lambda_{3} = 0$

We know that, <br>
any given matrix $A$ of size $m$ by $n$ can be decomposed into $A = UDV^T$<br>
where,<br>
U -> $m \times m$ orthogonal<br>
D -> $m \times n$ diagonal<br>
V -> $n \times n$ orthogonal<br>

Therefore, singular values of $A$ has to be just two i.e, $\sigma_{1} = \sqrt{\lambda_{1}} = \sqrt{6}$ ,and $\sigma_{2} = \sqrt{\lambda_{2}} = \sqrt{1} = 1$

Thus, diagonal matrix, $D = \begin{pmatrix}
\sqrt{6}&0&0\\
0&1&0\\
\end{pmatrix}$


Next, <br>
eigenvector for $\lambda_{1} = 6$ with $(A - \lambda I)u = 0$<br>
we get, <br>
$\begin{pmatrix}
1-6&0&1\\
0&1-6&2\\
1&2&5-6\\
\end{pmatrix} \cdot \begin{pmatrix}
x\\
y\\
z\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
0\\
\end{pmatrix}$

$\begin{pmatrix}
-5&0&1\\
0&-5&2\\
1&2&-1\\
\end{pmatrix} \cdot \begin{pmatrix}
x\\
y\\
z\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
0\\
\end{pmatrix}$

$\Rightarrow -5x + z = 0$<br>
and, $-5y + 2z = 0$<br>
and, $x + 2y -z = 0$

$\Rightarrow z = 5x$, and $y = 2x$<br>
$\Rightarrow x=1, y = 2$ and $z = 5$<br> So, eigenvector $v_{1} = \begin{pmatrix}
1\\
2\\
5\\
\end{pmatrix}$

Now, normalizing eigenvector, $v_{1} = \frac{1}{\lVert v_{1} \rVert}v_{1} = \frac{1}{\lVert \sqrt{1^2 + 2^2 + 5^2} \rVert}v_{1} = \frac{1}{\sqrt{30}}\begin{pmatrix}
1\\
2\\
5\\
\end{pmatrix}$

Next, <br>
eigenvector for $\lambda_{2} = 1$ with $(A - \lambda I)u = 0$<br>
we get, <br>
$\begin{pmatrix}
1-1&0&1\\
0&1-1&2\\
1&2&5-1\\
\end{pmatrix} \cdot \begin{pmatrix}
x\\
y\\
z\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
0\\
\end{pmatrix}$

$\begin{pmatrix}
0&0&1\\
0&0&2\\
1&2&4\\
\end{pmatrix} \cdot \begin{pmatrix}
x\\
y\\
z\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
0\\
\end{pmatrix}$

$\Rightarrow z = 0$<br>
and, $2z = 0$<br>
and, $x + 2y + 4z = 0$

$\Rightarrow x = -2, y = 1$, and $z = 0$ and eigenvector $v_{2} = \begin{pmatrix}
-2\\
1\\
0\\
\end{pmatrix}$

Now, normalizing eigenvector, $v_{2} = \frac{1}{\lVert v_{2} \rVert}v_{2} = \frac{1}{\lVert \sqrt{(-2)^2 + 1^2 + 0^2} \rVert}v_{2} = \frac{1}{\sqrt{5}}\begin{pmatrix}
-2\\
1\\
0\\
\end{pmatrix}$


Next, <br>
eigenvector for $\lambda_{3} = 0$ with $(A - \lambda I)u = 0$<br>
we get, <br>
$\begin{pmatrix}
1-0&0&1\\
0&1-0&2\\
1&2&5\\
\end{pmatrix} \cdot \begin{pmatrix}
x\\
y\\
z\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
0\\
\end{pmatrix}$

$\begin{pmatrix}
1&0&1\\
0&1&2\\
1&2&5\\
\end{pmatrix} \cdot \begin{pmatrix}
x\\
y\\
z\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
0\\
\end{pmatrix}$

$\Rightarrow x+ z = 0$<br>
and, $y + 2z = 0$<br>
and, $x + 2y + 5z = 0$

$\Rightarrow z = -x$ and $y = 2x$ So, $x =1, y =2$ and $z = -1$ and eigenvector $v_{3} = \begin{pmatrix}
1\\
2\\
-1\\
\end{pmatrix}$

Now, normalizing eigenvector $v_{3} = \frac{1}{\lVert v_{3} \rVert}v_{3} = \frac{1}{\lVert \sqrt{1^2 + 2^2 + (-1)^2} \rVert}v_{3} = \frac{1}{\sqrt{6}}\begin{pmatrix}
1\\
2\\
-1\\
\end{pmatrix}$



Therefore, $V = (v_{1}\quad v_{2}\quad v_{3}) = \begin{pmatrix}
1/\sqrt{30}&-2/\sqrt{5}&1/\sqrt{6}\\
2/\sqrt{30}&1/\sqrt{5}&2/\sqrt{6}\\
5/\sqrt{30}&0&-1/\sqrt{6}\\
\end{pmatrix}$

Next, using $\sigma_{1}u_{1} = Av_{1}$ and $\sigma_{2}u_{2} = Av_{2}$

$\Rightarrow \sigma_{1}u_{1} = \frac{1}{\sqrt{30}}\begin{pmatrix}
1&0&1\\
0&1&2\\
\end{pmatrix}\begin{pmatrix}
1\\
2\\
5\\
\end{pmatrix}$


$u_{1} = \frac{1}{\sqrt{6}}\frac{1}{\sqrt{30}}\begin{pmatrix}
6\\
12\\
\end{pmatrix}$

$u_{1} = \frac{1}{\sqrt{180}}\begin{pmatrix}
6\\
12\\
\end{pmatrix}$


next, <br>
$\sigma_{2}u_{2} = Av_{2}$<br>
$\Rightarrow u_{2} = \begin{pmatrix}
1&0&1\\
0&1&2\\
\end{pmatrix}\frac{1}{\sqrt{5}}\begin{pmatrix}
-2\\
1\\
0\\
\end{pmatrix}$

$\Rightarrow u_{2} = \frac{1}{\sqrt{5}}\begin{pmatrix}
-2\\
1\\
\end{pmatrix}$

Therefore, $U = (u_{1} \quad u_{2}) = \begin{pmatrix}
6/\sqrt{180}&-2/\sqrt{5}\\
12/\sqrt{180}&1/\sqrt{5}\\
\end{pmatrix}$

In [21]:
U = np.array([[6/np.sqrt(180), -2/np.sqrt(5)],
              [12/np.sqrt(180), 1/np.sqrt(5)]])

D = np.array([[np.sqrt(6), 0, 0],
              [0, 1, 0]])

V = np.array([[1/np.sqrt(30), -2/np.sqrt(5), 1/np.sqrt(6)],
              [2/np.sqrt(30), 1/np.sqrt(5), 2/np.sqrt(6)],
              [5/np.sqrt(30), 0, -1/np.sqrt(6)]])

UDVT = np.matmul(np.matmul(U, D), V.T)

# Round the elements to two decimal points
result_rounded = np.round(UDVT, 2)

print("Resultant matrix of UDV^T")
print(result_rounded)

Resultant matrix of UDV^T
[[ 1. -0.  1.]
 [-0.  1.  2.]]


<b> Solution (e) </b> 

Here, $A^TA = \begin{pmatrix}
1&3\\
1&3\\
\end{pmatrix}\begin{pmatrix}
1&1\\
3&3\\
\end{pmatrix}$

$\Rightarrow A^TA = \begin{pmatrix}
10&10\\
10&10\\
\end{pmatrix}$

Eigenvalues $det(A - \lambda) = 0$<br>

$\Rightarrow (10 - \lambda)(10 - \lambda) -100 - 0$<br>
$\Rightarrow 100 - 10\lambda -10\lambda + \lambda^2 - 100 = 0$<br>
$\Rightarrow \lambda^2 - 20\lambda = 0$<br>
$\Rightarrow \lambda(\lambda - 20) = 0$<br>

$\Rightarrow \lambda_{1} = 20$ and $\lambda_{2} = 0$

Here, singular value of matrix $A$ are $\sigma_{1} = \sqrt{20}$ and $\sigma_{2} = 0$

Hence, diagonal matrix, $D = \begin{pmatrix}
\sqrt{20}&0\\
0&0\\
\end{pmatrix}$

Next, eigenvector when $\lambda_{1} = 20$ with $(A - \lambda I)u = 0$<br>

we get, <br>
$\begin{pmatrix}
10-20&10\\
10&10-20\\
\end{pmatrix}\begin{pmatrix}
x\\
y\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
\end{pmatrix}$

$\Rightarrow -10x + 10y = 0$<br>
and, $10x -10y = 0$

$\Rightarrow x = y = 1$ and eigenvector $v_{1} = \begin{pmatrix}
1\\
1\\
\end{pmatrix}$

now, normalizing eigenvector $v_{1} = \frac{1}{\lVert v_{1}\rVert}v_{1} = \frac{1}{\lVert \sqrt{1^2 + 1^2}\rVert}v_{1} = \frac{1}{\sqrt{2}}\begin{pmatrix}
1\\
1\\
\end{pmatrix}$



Next, eigenvector when $\lambda_{2} = 0$ with $(A - \lambda I)u = 0$<br>

we get, <br>
$\begin{pmatrix}
10-0&10\\
10&10-0\\
\end{pmatrix}\begin{pmatrix}
x\\
y\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
\end{pmatrix}$

$\Rightarrow 10x + 10y = 0$<br>
and, $10x +10y = 0$

$\Rightarrow x = 1, y = -1$ and eigenvector $v_{2} = \begin{pmatrix}
1\\
-1\\
\end{pmatrix}$

now, normalizing eigenvector $v_{2} = \frac{1}{\lVert v_{2}\rVert}v_{2} = \frac{1}{\lVert \sqrt{1^2 + (-1)^2}\rVert}v_{2} = \frac{1}{\sqrt{2}}\begin{pmatrix}
1\\
-1\\
\end{pmatrix}$

Therefore, $V = (v_{1}\quad v_{2}) = \frac{1}{\sqrt{2}}\begin{pmatrix}
1&1\\
1&-1\\
\end{pmatrix}$

Now using $\sigma_{1}u_{1} = Av_{1}$

$\sqrt{20}u_{1} = \begin{pmatrix}
1&1\\
3&3\\
\end{pmatrix}\frac{1}{\sqrt{2}}\begin{pmatrix}
1\\
1\\
\end{pmatrix}$

$\Rightarrow u_{1} = \frac{1}{\sqrt{20}}\frac{1}{\sqrt{2}}\begin{pmatrix}
1\\
1\\
\end{pmatrix}\begin{pmatrix}
1&1\\
3&3\\
\end{pmatrix}$

$\Rightarrow u_{1} = \frac{1}{\sqrt{40}}\begin{pmatrix}
2\\
6\\
\end{pmatrix} = \frac{1}{\sqrt{10}}\begin{pmatrix}
1\\
3\\
\end{pmatrix} $

Next, to get, $u_{2}$ using, $u_{1}\cdot u{2}  = 0$

$\Rightarrow \begin{pmatrix}
1/\sqrt{10}\\
3/\sqrt{10}\\
\end{pmatrix}\begin{pmatrix}
x\\
y\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
\end{pmatrix}$

$\Rightarrow x = 3, y = -1$ and normalized $u_{2} = \frac{1}{\lVert \sqrt{3^2 + (-1)^2}\rVert}u_{2} = \frac{1}{\sqrt{10}}\begin{pmatrix}
3\\
-1\\
\end{pmatrix}$

Therefore, $U = \frac{1}{\sqrt{10}}\begin{pmatrix}
1&3\\
3&-1\\
\end{pmatrix}$

In [8]:
import numpy as np

U = (1 / np.sqrt(10)) * np.array([[1, 3], [3, -1]])
D = np.array([[np.sqrt(20), 0], [0, 0]])
V = (1 / np.sqrt(2)) * np.array([[1, 1], [1, -1]])

UDVT = np.matmul(np.matmul(U, D), V.T)

# Round the elements to two decimal points
result_rounded = np.round(UDVT, 2)

print("Resultant matrix of UDV^T")
print(result_rounded)

Resultant matrix of UDV^T
[[1. 1.]
 [3. 3.]]


<b> Solution (f) </b>

Here, $A^TA = \begin{pmatrix}
1&3\\
1&3\\
1&3\\
\end{pmatrix} \begin{pmatrix}
1&1&1\\
3&3&3\\
\end{pmatrix}$ 

$\Rightarrow A^TA = \begin{pmatrix}
10&10&10\\
10&10&10\\
10&10&10\\
\end{pmatrix}$

Eigenvalue of $A^TA: det(A - \lambda I)  =0$

$\Rightarrow \begin{pmatrix}
10 - \lambda&10&10\\
10&10-\lambda&10\\
10&10&10-\lambda\\
\end{pmatrix} \begin{pmatrix}
x\\
y\\
z\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
0\\
\end{pmatrix}$

$\Rightarrow (10 - \lambda)[(10 - \lambda)(10 - \lambda) -100] - 10[10(10 - \lambda) -100] + 10[100 - 10(10 - \lambda)] = 0$<br>
$\Rightarrow (10 - \lambda)[100 - 10\lambda - 10\lambda + \lambda^2 -100] - 10[100 - 10\lambda -100] + 10[100 - 100 + 10 \lambda)] = 0$<br>

$\Rightarrow (10 - \lambda)(\lambda^2 - 20\lambda) + 100\lambda + 100\lambda = 0$<br>

$\Rightarrow 10\lambda^2 -20\lambda - \lambda^3 + 20\lambda^2 + 100\lambda + 100\lambda = 0$<br>

$\Rightarrow -\lambda^3 + 30\lambda^2 = 0$<br>
$\Rightarrow \lambda^2(\lambda - 30) = 0$


$\Rightarrow \lambda_{1} = 30$ and $\lambda_{2}= 0$, $\lambda_{3} = 0$


We know that, <br>
any given matrix $A$ of size $m$ by $n$ can be decomposed into $A = UDV^T$<br>
where,<br>
U -> $m \times m$ orthogonal<br>
D -> $m \times n$ diagonal<br>
V -> $n \times n$ orthogonal<br>

<b>Here, $D$ would be of size $2 \times 3$, where positive singular value of $A$, $\sigma_{1} = \sqrt{30}$</b>

$\Rightarrow D = \begin{pmatrix}
\sqrt{30}&0&0\\
0&0&0\\
\end{pmatrix}$\


Next, for eigenvector when $\lambda_{1} = 30$ with $(A - \lambda I)u = 0$ <br>
we get, <br>

$\begin{pmatrix}
10-30&10&10\\
10&10-30&10\\
10&10&10-30\\
\end{pmatrix} \begin{pmatrix}
x\\
y\\
z\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
0\\
\end{pmatrix}$


$\Rightarrow -20x + 10y + 10z = 0$<br>
and, $10x - 20y + 10z = 0$<br>
and, $10x + 10y -20z = 0$<br>

$\Rightarrow x = y= z =1$<br>

$v_{1} = \begin{pmatrix}
1\\
1\\
1\\
\end{pmatrix}$

Now, normalized eigenvector $v_{1} = \frac{1}{\lVert v_{1} \rVert}v_{1} = \frac{1}{\sqrt{1^2 + 1^2 + 1^2}} = \frac{1}{\sqrt{3}}\begin{pmatrix}
1\\
1\\
1\\
\end{pmatrix}$


Next, for eigenvector when $\lambda_{2} = 0$ and $\lambda_{3} = 0$ with $(A - \lambda I)u = 0$ <br>
we get, <br>

$\begin{pmatrix}
10-0&10&10\\
10&10-0&10\\
10&10&10-0\\
\end{pmatrix} \begin{pmatrix}
x\\
y\\
z\\
\end{pmatrix} = \begin{pmatrix}
0\\
0\\
0\\
\end{pmatrix}$


$\Rightarrow 10x + 10y + 10z = 0$<br>
and, $10x +10y + 10z = 0$<br>
and, $10x + 10y + 10z = 0$<br>

This system of equation is degenrate, $x, y, z$ can be any set of numbers. However, as $U$ is needed to be orthogonal we pick values of $x, y, z$ for $v_{2}$ and $v_{3}$ such that $v_{2}\cdot v_{3} = 0$

If $v_{1} = \begin{pmatrix}
1\\
-1\\
0\\
\end{pmatrix}$ we have $v_{2} = \begin{pmatrix}
1\\
1\\
-2\\
\end{pmatrix}$

Now, normalized eigenvector $v_{2} = \frac{1}{\lVert v_{2} \rVert}v_{2} = \frac{1}{\sqrt{1^2 + (-1)^2 + 0^2}} = \frac{1}{\sqrt{2}}\begin{pmatrix}
1\\
-1\\
1\\
\end{pmatrix}$

and, normalized eigenvector $v_{3} = \frac{1}{\lVert v_{3} \rVert}v_{3} = \frac{1}{\sqrt{1^2 + 1^2 + (-2)^2}} = \frac{1}{\sqrt{6}}\begin{pmatrix}
1\\
1\\
-2\\
\end{pmatrix}$

<b>Therefore, $V = (v_{1}\quad v_{2}\quad v_{3}) = \begin{pmatrix}
1/\sqrt{3}&1/\sqrt{2}&1/\sqrt{6}\\
1/\sqrt{3}&-1/\sqrt{2}&1/\sqrt{6}\\
1/\sqrt{3}&1/\sqrt{2}&-2/\sqrt{6}\\
\end{pmatrix}$</b>

Now, using $\sigma_{1}u_{1} = Av_{1}$

$\Rightarrow \sqrt{30}u_{1} =\begin{pmatrix}
1&1&1\\
3&3&3\\
\end{pmatrix} \frac{1}{\sqrt{3}}\begin{pmatrix}
1\\
1\\
1\\
\end{pmatrix}$

$\Rightarrow u_{1} = \frac{1}{\sqrt{30}}\frac{1}{\sqrt{3}}\begin{pmatrix}
3\\
9\\
\end{pmatrix}$<br>


$\Rightarrow u_{1} = \frac{1}{\sqrt{90}}\begin{pmatrix}
3\\
9\\
\end{pmatrix} = \frac{1}{\sqrt{10}}\begin{pmatrix}
1\\
3\\
\end{pmatrix}$

Next, $u_{2}$ needs to be orthogonal as well, Therefore $u_{2} = \begin{pmatrix}
3\\
-1\\
\end{pmatrix}$ and normalized $u_{2} = \frac{1}{\sqrt{10}}\begin{pmatrix}
3\\
-1\\
\end{pmatrix}$

<b> Therefore, $U = (u_{1}\quad u_{2}\quad u_{3}) = \frac{1}{\sqrt{10}}\begin{pmatrix}
1&3\\
3&-1\\
\end{pmatrix}$

In [10]:
import numpy as np

U = (1 / np.sqrt(10)) * np.array([[1, 3],
                                  [3, -1]])

D = np.array([[np.sqrt(30), 0, 0],
              [0, 0, 0]])

V = np.array([[1/np.sqrt(3), 1/np.sqrt(2), 1/np.sqrt(6)],
              [1/np.sqrt(3), -1/np.sqrt(2), 1/np.sqrt(6)],
              [1/np.sqrt(3), 1/np.sqrt(2), -2/np.sqrt(6)]])

UDVT = np.matmul(np.matmul(U, D), V.T)

# Round the elements to two decimal points
result_rounded = np.round(UDVT, 2)

print("Resultant matrix of UDV^T")
print(result_rounded)


Resultant matrix of UDV^T
[[1. 1. 1.]
 [3. 3. 3.]]


------------------------------  

<b> Question 2</b> 

Prove proposition 7.31

<b> Proposition 7.31: Let $A$ be any matrix. Then the eigenvalues of $A^TA$ are positive or zero</b>

<b> Solution 2 </b> 

Let $\lambda_{1}, \lambda_{2}, \cdots, \lambda_{n}$ be the eigenvalues with eigenvectors $v_{1}, v_{2}, \cdots, v_{n}$.

Then, as we know $Av = \lambda v$, so for any randomly chosen  $v_{j}$

$A^TAv_{j} = \lambda_{j}v_{j}$

We also know that, <br>
if $A$ is any matrix then $A^TA$ is a symmetric matrix.

$\Rightarrow A^TA$ is orthogonally diagonalizable<br>
$\Rightarrow$ eigenvectors are orthonormal

Now taking norm square:<br>

$\lVert Av_{j} \rVert^2 = Av_{j}\cdot Av_{j}$

$\qquad = (Av_{j})^T Av_{j}\qquad$ (Since $(u\cdot v = u^T\cdot v))$
$\qquad = A^T V_{j}^T Av_{j}$<br>
$\qquad = v_{j}^T A^TAv_{j}$<br>
$\qquad = v_{j}^T \lambda_{j}v_{j}$<br>
$\qquad = \lambda_{j} (v_{j}\cdot v_{j}) = \lambda_{j}$<br>

Now, we have $\lambda_{j} = \lVert Av_{j} \rVert^2$ i.e., $\ge 0$

$\Rightarrow \lambda_{j} \ge 0$<br>

Hence, all eigenvalues of $A^TA$ are either positive values or zeroes.

-------------------------------   

<b> Question 3</b> 

Let matrix $A$ have $k-$positive singular values. Show that rank of matrix $A$ is $k$

Hint: <br>
If matrix $X$ is invertible then $rank(XA) = rank(A)$ and $rank(AX) = rank(A)$

<b> Solution 3</b>

We know that, <br>
any given matrix $A$ of size $m$ by $n$ by SVD can be decomposed into $A = UDV^T$<br>
where,<br>
U -> $m \times m$ orthogonal<br>
D -> $m \times n$ diagonal<br>
V -> $n \times n$ orthogonal<br>

Now, since $U$ is orthogonal, it is invertible<br>
and, $U^{-1} = U^T$

Similarly, $V^{-1} = V^T$<br>
$\Rightarrow (V^T)^{-1} = V$<br>
$\Rightarrow V^T$ is invertible

We are given, <br>
If matrix $X$ is invertible then $rank(XA) = rank(A)$ and $rank(AX) = rank(A)$

$\Rightarrow rank(A) = rank(UDV^T)$<br>
$\qquad = rank(DV^T)$<br>
$\qquad = rank(D)$<br>
$\qquad = k$

-----------------------------    

<b> Question 4</b> 

Prove proposition 7.33 

<b> Proposition 7.33: Let $A$ be an $m$ by $n$ matrix with factorization given by $A = UDV^T$. Let matrix $A$ have $k \le n$ positive singular values. Then we have the following:<br>
   (a) The set of vectors $\{u_{1}, u_{2}, \cdots, u_{k}\}$ form an orthonormal basis for the column space of matrix $A$.<br>
    (b) The set of vectors $\{v_{1}, v_{2}, \cdots, v_{k}\}$ form an orthonormal basis for the row space of matrix $A$<br>
    (c) The set of vectors $\{v_{k+1}, v_{K+2}, \cdots, v_{n}\}$ form an orthonormal basis for the null space of matrix $A$

---------------------------- 

<b> Question 5 </b> 

Prove that the singular values $\sigma_{1}, \sigma_{2}, \dots \sigma_{n}$ of an $m$ by $n$ matrix $A$ are unique. 

<b> Solution 5</b> 

To get singular values of an $m$ by $n$ matrix $A$, we take eigenvalues of $A^TA$ and thereby, singular values as square roots.

As, $A^TA$ makes it a $n$ by $n$ matrix, and we know that, for a square matrix, $A$ with $\lambda$ eigenvalues and $u$ eigenvector. The eigenvalue $\lambda$ is unique.

Therefore, singular values or square roots of those eigenvalues must also be unique. 

Hence, proved

---------------------------------- 

<b> Question 6</b> 

Prove that the column vectors of the orthogonal matrix $U$ in $A = UDV^T$ are the eigenvectors of $AA^T$

<b> Solution </b>

By $SVD$, we have<br>

$A  = UDV^T$

$\Rightarrow AA^T = UDV^T (UDV^T)^T$<br>

$\qquad = (UDV^T) (V^T)^T U^TD^T$

$\qquad = UD\cdot V^TV \cdot U^TD^T$

$\qquad = U (DD^T)U^T$

if $D^{'} = DD^T$<br>
then, $AA^T = UD^{'}U^T$

Since, $U$ is orthogonal, its inverse is $U^T$

Next, <br>

$U^T(AA^T)U = U^TU \cdot (D^{'}) \cdot U^TU$

$\Rightarrow U^T (AA^T) U = D^{'}$

$\Rightarrow U$ diagonalizes $AA^T$ and the columns of $A$ are eigenvectors of $AA^T$

------------------------- 

<b> Question 7</b> 

Prve that singular values of $A$ and $A^T$ are identical

<b> Solution 7 </b>

The singular values of a matrix $A$ are given by the square roots of the eigenvalues of $A^TA$: $\lambda_{1}, \lambda_{2},\cdots, \lambda_{n}$

Similarly, singular values of a matrix $A^T$ are given by the sqaure roots of the eigenvalues of $(A^T)^TA^T$: $\delta_{1}, \delta_{2}, \cdots, \delta_{n}$

We know that, <br>

The eigenvalues of the transposed matrix, $A^T$, are exactly the eigenvlues of $A$.

$\Rightarrow$ eigenvalues of transposed matrix $(A^T)^TA^T = $eigenvalues of $A^TA$

$\Rightarrow \delta_{1} = \lambda_{1}, \delta_{2} = \lambda_{2}, \cdots, \delta_{n} = \lambda_{n}$

$\Rightarrow \sqrt{\delta_{1}} = \sqrt{\lambda_{1}}, \sqrt{\delta_{2}} = \sqrt{\lambda_{2}}, \cdots, \sqrt{\delta_{n}} = \sqrt{\lambda_{n}}$

Hence, proved singular value of $A^T$ and $A$ are equal

--------------------- 

<b> Question 8 </b> 

Let $T: \mathbb{R}^n \to \mathbb{R}^m$ be a linear transformation given by $T(x) = Ax$, where $A$ is an $m$ by $n$ matrix. Let singular value decomposition $A = UDV^T$ with $k \le n$ positive singular values of matrix $A$. Prove the following results: 

(a) The set of vectors $u_{1}, u_{2}, \dots u_{k}$ form an orthogonal basis for the range of $T$.<br>
(b) The set of vectors $v_{k+1}, v_{k+2},\dots v_{n}$ form an orthogonal basis for the kernel of $T$